### ISSUE TITLE
Problem building x265

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#112]
see: https://pastee.org/sspfx
deleting x265-git and restarting the script didn't help either, .ini used:
>[compiler list]
msys2Arch=2
arch=1
free=2
ffmbc=1
vpx=1
x264=1
x265=1
other265=1
flac=1
mediainfo=1
soxB=1
ffmpegB=1
ffmpegUpdate=1
ffmpegChoice=1
mp4box=1
mplayer=1
mpv=2
mkv=1
cores=8
deleteSource=1
strip=1
pack=2

**Comment by LigH-de** [comment]
The reason is probably that the multilib cmake parameters changed. There will now be a multilib EXE which can also be linked dynamically into using applications as if it were a DLL, because it will also export the API.

To be on the safe side, I would recommend to strip this result not with `--strip-all` but only with `strip-unneeded`.
