### ISSUE TITLE
Can't configure ffmpeg with CUDA SDK 10.1

### ISSUE THREAD

**Issue by kliffgomel** [jb-alvarado/media-autobuild_suite#1124]
check_nvcc
test_nvcc
BEGIN /tmp/ffconf.lNSwlHfR/test.cu
    1	extern "C" {
    2	    __global__ void hello(unsigned char *data) {}
    3	}
END /tmp/ffconf.lNSwlHfR/test.cu
nvcc -ptx -c -o D:/ffmpeg-autobuild/msys64/tmp/ffconf.lNSwlHfR/test.o D:/ffmpeg-autobuild/msys64/tmp/ffconf.lNSwlHfR/test.cu
nvcc fatal   : Cannot find compiler 'cl.exe' in PATH
ERROR: failed checking for nvcc.

I try custom_profile file like this:
_cuda_basepath="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA"
_cuda_version=v10.1
_msvc_basepath="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC"
_msvc_version=14.16.27023
_msvc_hostarch=x64
_msvc_targetarch=x64
export CUDA_PATH=$(cygpath -sm "${_cuda_basepath}")/${_cuda_version}
export PATH=$PATH:$(dirname "$(cygpath -u "\\${_msvc_basepath}\\${_msvc_version}\bin\Host\\${_msvc_hostarch}\\${_msvc_targetarch}\cl.exe")")
export PATH=$PATH:$CUDA_PATH/bin

and like this:
_cuda_path="/c/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin"
_msvc_path="/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"
export PATH=$PATH:$_cuda_path
export PATH=$PATH:$_msvc_path

[config.log](https://github.com/jb-alvarado/media-autobuild_suite/files/2930506/config.log)

**Comment by schmidthubert** [comment]
First: for a proper fix please wait for Ricardo. :+1: 

For a quick fix, here's my line which goes into the helper script right below

`get_cl_path() {`
`    command -v cl.exe &>/dev/null && return 0`

put your path to the cl.exe like I did here:

`command -v "$(cygpath -sm "C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\")/VC/bin/cl.exe" &>/dev/null && return 0`

As you can see,  even VS 2013's cl.exe is good enough to do the job, and so is VS 2015 :+1:  I'm too lazy to update my Win7 box with VS 2017 (which I have in my Win10 installations), and since vswhere even with -legacy switch doesn't work correctly then I don't bother and don't fiddle with it. It simply works, nvcc.exe is certainly/probably/most likely searching the Windows Path for cl.exe anyway. So if `where cl.exe` in a CMD window finds it you should be fine. :+1:

**Comment by wiiaboo** [comment]
> _msvc_path="/c/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/cl.exe"

Remove the `cl.exe` from the end.

Where's the logs.zip?

**Comment by kliffgomel** [comment]
> Remove the `cl.exe` from the end.

Yes it works. Although the example recommended:
...
export PATH=$PATH:$(dirname "$(cygpath -u "\${_msvc_basepath}\${_msvc_version}\bin\Host\${_msvc_hostarch}\${_msvc_targetarch}\cl.exe")")
...
But now there was another problem:

check_pkg_config libx265 x265 x265.h x265_api_get
test_pkg_config libx265 x265 x265.h x265_api_get
pkg-config --exists --print-errors x265
check_func_headers x265.h x265_api_get -LD:/ffmpeg-autobuild/local64/lib -lx265 -lstdc++ -lgcc
test_ld cc -LD:/ffmpeg-autobuild/local64/lib -lx265 -lstdc++ -lgcc
test_cc -LD:/ffmpeg-autobuild/local64/lib
BEGIN /tmp/ffconf.12N4NYlW/test.c
    1	#include <x265.h>
    2	#include <stdint.h>
    3	long check_x265_api_get(void) { return (long) x265_api_get; }
    4	int main(void) { int ret = 0;
    5	 ret |= ((intptr_t)check_x265_api_get) & 0xFFFF;
    6	return ret; }
END /tmp/ffconf.12N4NYlW/test.c
gcc -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -U__STRICT_ANSI__ -D__USE_MINGW_ANSI_STDIO=1 -D__printf__=__gnu_printf__ -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -DOPJ_STATIC -mthreads -mtune=generic -O2 -pipe -DLIBTWOLAME_STATIC -DLIBXML_STATIC -DKVZ_STATIC_LIB -IC:/PROGRA~1/NVIDIA~2/CUDA/v10.1/include -std=c11 -fomit-frame-pointer -ID:/ffmpeg-autobuild/local64/include/harfbuzz -ID:/ffmpeg-autobuild/local64/include/freetype2 -ID:/ffmpeg-autobuild/local64/include/fribidi -ID:/ffmpeg-autobuild/local64/include/freetype2 -DLIBXML_STATIC -ID:/ffmpeg-autobuild/msys64/mingw64/include/libxml2 -ID:/ffmpeg-autobuild/local64/include/freetype2 -ID:/ffmpeg-autobuild/local64/include/freetype2 -ID:/ffmpeg-autobuild/local64/include/fribidi -ID:/ffmpeg-autobuild/msys64/mingw64/include/openjpeg-2.3 -ID:/ffmpeg-autobuild/local64/include/opus -ID:/ffmpeg-autobuild/local64/include/opus -LD:/ffmpeg-autobuild/local64/lib -c -o /tmp/ffconf.12N4NYlW/test.o /tmp/ffconf.12N4NYlW/test.c
In file included from D:/ffmpeg-autobuild/msys64/tmp/ffconf.12N4NYlW/test.c:1:
D:/ffmpeg-autobuild/local64/include/x265.h:1801:43: error: unknown type name 'bool'; did you mean '_Bool'?
 x265_zone *x265_zone_alloc(int zoneCount, bool isZoneFile);
                                           ^~~~
                                           _Bool
D:/ffmpeg-autobuild/msys64/tmp/ffconf.12N4NYlW/test.c: In function 'check_x265_api_get':
D:/ffmpeg-autobuild/msys64/tmp/ffconf.12N4NYlW/test.c:3:40: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
 long check_x265_api_get(void) { return (long) x265_api_get; }
                                        ^
ERROR: x265 not found using pkg-config 

[logs.zip](https://0x0.st/zoL3.zip)

**Comment by schmidthubert** [comment]
It's broken again, because x265 team changed something. Report it to ffmpeg team to fix it.

**Comment by wiiaboo** [comment]
> Yes it works. Although the example recommended:
> ...
> export PATH=$PATH:$(**dirname** "$(cygpath -u "${_msvc_basepath}${_msvc_version}\bin\Host${_msvc_hostarch}${_msvc_targetarch}\cl.exe")")

Notice what you deleted.

**Comment by kliffgomel** [comment]
> > export PATH=$PATH:$(**dirname** "$(cygpath -u "${_msvc_basepath}${_msvc_version}\bin\Host${_msvc_hostarch}${_msvc_targetarch}\cl.exe")")
> 
> Notice what you deleted.

Of course you are right, but everything began today with the fact that for some reason your version stopped working for me ...

**Comment by kliffgomel** [comment]
https://trac.ffmpeg.org/ticket/7772

**Comment by schmidthubert** [comment]
LOL, how many times, is it Alzheimer??? :-1:

**Comment by schmidthubert** [comment]
Oh, looks x265 team is pissed off because some1 gave it straight to them. They even put a "blocked" on [the issue](https://bitbucket.org/multicoreware/x265/issues/472/yet-again-you-have-broken-c-compilation-by). Hmm, that's the problem with these "community projects" without any real bosses. At work they would be summoned and would receive a warning letter for repeated fuckup, but here these kids can do whatever they want. :-1:  Luckily in the case of x265 it doesn't matter much anymore. The project doesn't make much progress anymore anyway. I don't even if the v3.0 tag was justified. Simply pin it to [31ab7e0](https://bitbucket.org/multicoreware/x265/commits/31ab7e09a3b5b15ffcc532826d4dd5d37e611483) an be done with it. :+1:

**Comment by Helenerineium** [comment]
"blocker" is the highest priority you can choose when creating a issue, you can verify yourself by going to https://bitbucket.org/multicoreware/x265/issues/new, so I don't see what's wrong with that.

**Comment by schmidthubert** [comment]
Ah, thank you! Nevertheless the ticket says "Former user created an issue", so?

**Comment by schmidthubert** [comment]
And what consequences does blocker have anyway? It's just on paper isn't it? Nothing happened at all so far, next commit is up already. Would've taken only 3 mins to revert that crap patch.

**Comment by GyanD** [comment]
x265 is not one of these "community projects". It is dual-licensed and developed by a commercial entity - Multicoreware Inc. The latest commits I see are all by employees.

**Comment by schmidthubert** [comment]
Thanks for all the explanations. :+1:  What's the explanation for the repeated fuckup of these pros then and not reverting it immediately? And the user probably kicked out from the looks of it for just sharply speaking his probably fed up mind (this is the 3rd time now)? Can't they take the criticism especially since this is not a first? Anyway, you probably couldn't answer that. But professionally is something else, that much is for sure. :cry:

**Comment by schmidthubert** [comment]
OK thank you! :+1: But still: a blocker is and should do what exactly then? Should it freeze development and mean "fix that ticket first and right now" or whatever or any priority at all or like I said "just on paper"? And why doesn't at least somebody put a one liner as a reply there like "oh sorry, will check asap" or whatever, is asking for just a little feedback too much?

**Comment by 1480c1** [comment]
I guess a blocker means that either it will block compilation or normal use. Probably, they are all asleep or on a 24 hour coffee break, like the ones that apple has.

**Comment by wiiaboo** [comment]
A blocker/blocking issue means no new releases/tags should be done until the issue is fixed, i.e. highest priority, usually.

**Comment by wiiaboo** [comment]
> What's the explanation for the repeated fuckup of these pros then and not reverting it immediately? 

Because it's not really the commit that's an issue, it's a specific type used in the commit. Usually a revert can be done, but it's arguably better to just fix the issue in a smaller commit done ASAP, instead of committing a revert and then reapplying the same commit with the fixed issue.

**Comment by schmidthubert** [comment]
Thanks a lot Ricardo! :+1: I'll shut up about x265 "teamwork" now and have a coffee! :coffee:

**Comment by wiiaboo** [comment]
After installing cuda sdk and msvs again from scratch after resetting the OS, I can't reproduce this issue.
Your MSVS installation is probably broken.
