### ISSUE TITLE
MSVS usage

### ISSUE THREAD

**Issue by roman-minyaylov** [jb-alvarado/media-autobuild_suite#1142]
Is it possible to use VS 2017 compiler?

I'm unable to link static libraries to MSVC DLL, so, want to use MSVC compiler to get compatible static libraries.

**Comment by 1480c1** [comment]
Using compilers outside of mingw gcc is out of scope for this suite. Also because the commands and flags used in the suite are incompatible with cl.exe. I'm not sure about the clang supplied with VS 2017.
You can try with each individual package to see if they support MSVC compilers and compile them separately.

**Comment by wiiaboo** [comment]
Like @1480c1 said, out of scope for the suite. There's only one thing requiring MSVC because it doesn't work with gcc, otherwise it's not used for anything, nor will it at any point. Most of the stuff being built here will not work with it.
