### ISSUE TITLE
Compiling official ffmpeg 4.1.2 binaries

### ISSUE THREAD

**Issue by futurion** [jb-alvarado/media-autobuild_suite#1145]
Hello Ricardo,

a few months ago I asked for an option to compile official ffmpeg 4.0 release and you gave me instructions to modify some specific files, so it checks the official 4.0 release git instead of bleeding-edge-trunk git. I would like to compile now the latest available official build (4.1.2). How would I be able to do this the easiest way possible?

Thank you in advance, Tomaz.

**Comment by wiiaboo** [comment]
Same instructions, basically.
Change the ffmpeg git url to contain `#tag=n4.1.2` and that's it. There'll be broken configures because git master will contain or not have some external libraries that 4.1.2 has, so you have to either lookup what was removed/added since the 4.1.x branch (see http://git.videolan.org/?p=ffmpeg.git;a=blob;f=Changelog;h=ad7e82ffaea1f71faa71297656afec83ab5492ac;hb=HEAD) and remove any `--enable-*` that would break FFmpeg's configure.
Looking at the changelog, you'll have to remove `--enable-libdav1d` and `--enable-libndi-newtek` (the latter because the suite doesn't compile it anymore. You might also want to remove `--enable-cuda-nvcc` because it was called `--enable-cuda-sdk` and the checks are different. If you need this and libndi you might want to revert the suite commits that changed those for it to work.


(And this is why we don't support anything except git master.)

**Comment by futurion** [comment]
Thank you for your answer. I tried to follow the instructions you gave me before in post here (https://github.com/jb-alvarado/media-autobuild_suite/issues/888#issuecomment-410095838). Here you wrote to change the line that appears second time:
do_vcs "https://git.ffmpeg.org/ffmpeg.git"
with this one:
do_vcs "https://git.ffmpeg.org/ffmpeg.git#branch=release/4.0"

In the latest version of your script that line appears at lines: 1219, 1624, 2053.

I changed only line 1624 to:
do_vcs "https://git.ffmpeg.org/ffmpeg.git#branch=release/4.1"

But it doesn't work, it just always checks the latest git master instead. Is there maybe anything else I could try? Or did I maybe enter the wrong line or wrong syntax?

Also, how would I be possible to compile ffmpeg with ndi support now? Should I use some older script maybe? If so, which release does still support it?

Kind regards again, Tomaz.

**Comment by 1480c1** [comment]
How exactly did you check if it's from git head or release? Did you do ffmpeg --version?
For ndi, unless ndi sends out patches and sdk on their side, you cannot compile it since ffmpeg removed ndi code due to license violation.

**Comment by schmidthubert** [comment]
That's a wrong link, this should be correct:

https://git.ffmpeg.org/ffmpeg.git#tag=n4.1.2

**Comment by futurion** [comment]
Hey schmidthubert, thank you for this correction. Now it worked! I also see Ricardo wrote that same syntax up in his first post above, I overlooked it.

Regarding the package incompatibility, I only needed to comment-out #--enable-libdav1d, nothing else.

Thank you again!
