### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by laurfb** [jb-alvarado/media-autobuild_suite#127]
Hi. I wonder if VLC (http://www.videolan.org/) can be added (if it's worth) to media-autobuild_suite.
regards,
laur

**Comment by jb-alvarado** [comment]
In the very begin it was inside, but I had put it out. It takes very long until everything is done what it needed, it take allot of space and at the end it have less libs inside than the normal one. They also bring daily builds out what I know, and from the lib side is also not so interesting because they have all in already.

**Comment by wiiaboo** [comment]
I also agree.
[Win 32-bit Nightlies](http://nightlies.videolan.org/build/win32/last/)
[Win 64-bit Nightlies](http://nightlies.videolan.org/build/win64/last/)

Too many dependancies to add just for VLC and not really worth it.
