### ISSUE TITLE
[64-bit] mpv/vapoursynth build failed

### ISSUE THREAD

**Issue by masterkivat** [jb-alvarado/media-autobuild_suite#1287]
05:27:25 └ libplacebo-git .................................... [Updated]
05:27:25   Running git clone for mpv...
05:27:39 ┌ mpv git .................................. [Recently updated]
05:27:39 ├ Running bootstrap...
05:27:42 Installing python3-docutils... done
05:27:47 ├ Running configure...
05:28:01 ├ Running build...
Likely error:
video/filter/vf_vapoursynth.c.19.o:vf_vapoursynth.c:(.text+0x17c8): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `vsscript_getError'
video/filter/vf_vapoursynth.c.19.o:vf_vapoursynth.c:(.text+0x17f9): undefined reference to `vsscript_init'
video/filter/vf_vapoursynth.c.19.o:vf_vapoursynth.c:(.text+0x17f9): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `vsscript_init'
video/filter/vf_vapoursynth.c.19.o:vf_vapoursynth.c:(.text+0xc21): undefined reference to `vsscript_finalize'
video/filter/vf_vapoursynth.c.19.o:vf_vapoursynth.c:(.text+0xc21): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `vsscript_finalize'
collect2.exe: error: ld returned 1 exit status

Waf: Leaving directory `/build/mpv-git/build'
Build failed
 -> task in 'mpv' failed with exit status 1 (run with -v to display more information)
build failed. Check C:/media-autobuild_suite-master/build/mpv-git/ab-suite.build.log
This is required for other packages, so this script will exit.

[zpQG.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/3418496/zpQG.zip)

**Comment by pat357** [comment]
Can you check the 2 **.def** files in **/build/VapourSynth64-Portable-R46/build-64bit/** ?
Is one of the 2 .DEF files maybe empty ?

**Comment by masterkivat** [comment]
> 
> 
> Can you check the 2 **.def** files in **/build/VapourSynth64-Portable-R46/build-64bit/** ?
> Is one of the 2 .DEF files maybe empty ?

Both vapoursynth.def and vsscript.def are empty

**Comment by pat357** [comment]
That's what I suspected and this is the cause of your problem.

Replace the following lines in the file /build/media-suite_build.sh (lines 1558-1559 ...):
```bash
        for _file in vapoursynth vsscript; do
            gendef "../$_file.dll" >/dev/null 2>&1 |
```
by
```bash
        for _file in vapoursynth vsscript; do
            gendef - "../${_file}.dll" 2>/dev/null |
```

Delete both **vapoursynth-script.pc** and **vapoursynth.pc** from **/lib64/pkgconfig** to force the system to rebuild this .def files.
You can also delete **libvsscript.a** and **libvapoursynth.a** from /lib64 to make sure these will be replaced by the correct one.
If you use an editor to edit media-suite_build.sh, make sure it has an option to keep linux-line-ending (LF), so it doesn't convert the file to Windows line-ending (LF + CR).
Start the suite again, and it will build MPV correctly as it does on my system.

Note : the changes needed in the media-suite_build.sh are required because the author made a typo; I fixed it in my own file but forgot to mention it earlier. I'll tell him in case he misses this comment.

**Comment by pat357** [comment]
I guess there's still a typo in your latest patch  2bfe577 (https://github.com/jb-alvarado/media-autobuild_suite/commit/2bfe57795e5e790438b86b20c3bfe7f7a7de220e) 
```bash
gendef - "../$_file.dll" >/dev/null 2>&1 |
```
if you do  **">/dev/null 2>&1 |"** , both stdout & stderr will be redirected to null and there will never be any data going to the pipe. 
This will also create empty .def files.
Only stderr should go to null and stdout should go to the pipe to further be processed by sed.
Like this:
```bash
gendef - "../${_file}.dll" 2>/dev/null |
```
