### ISSUE TITLE
WebP sources from GitHub  ?

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#129]
I was wondering why you didn't use the GIT-repo instead of a fixed version (v43) download ?
Maybe you're not aware of the Repo : https://github.com/webmproject/libwebp/ ,  which is a mirror from  https://chromium.googlesource.com/webm/libwebp .

If you'd rather keep the 0.43 release, I can tell you the WebP offered by MinGW/Msys2 builds fine and integrates nice with ffmpeg. Another good ones I always use to build ffmpeg is WavPack & Libsnappy.

I was a bit surprised about the recently announced problems with the Utvideo/OpenSSL combo as I've been building exactly this combo for years (long before I found media-autobuils-suite) and I never have encountered any problems.  I believe there was MingW specific a patch for UTVideo at some time ..
If you want, I can dig it up and retest it , just ask if you're interested.

**Comment by wiiaboo** [comment]
WebP git failed compilation when I tried: http://i.fsbn.eu/JO74.txt
Didn't happen with last stable version.

Problem with using MinGW packages are mostly because they either don't build static libs or some kind of problem with the builds themselves, like libidn having -R flag that messes with GCC/FFmpeg.

mpv intermittently fails linking with GnuTLS for some reason, so that's why I prefer OpenSSL.

You're welcome to make a PR with those changes, if you want and can make it work for both 32 and 64-bits.

**Comment by wiiaboo** [comment]
Seems it was a GCC 5.x problem, it's fixed with a patch. And it needed -static-libgcc in LDFLAGS to be used in cmd.exe.

Wavpack is not needed, last time I discussed that with someone more knowledgeable about it, ffmpeg's native codec is fine.
