### ISSUE TITLE
Help: Guide to compile FFmpeg with OpenCL ICD

### ISSUE THREAD

**Issue by lars18th** [jb-alvarado/media-autobuild_suite#1301]
Hi,

I ask this here as I feel you know how to do it:

- I want to compile the FFmpeg using this suite with the OpenCL support enabled. The Nvidia Windows driver installs the runtime required libraries. So in any Windows machine the FFmpeg will work (as with the NVENC/NVDEC). In the FFmpeg documentation it's recommended to build using the ICD loader: https://trac.ffmpeg.org/wiki/HWAccelIntro#OpenCL. And the ICD Loader is opensource: https://github.com/KhronosGroup/OpenCL-ICD-Loader.

So I request about how to compile with it using the suite.
Any idea?
Thank you!

**Comment by 1480c1** [comment]
You could try to install `mingw-w64-x86_64-opencl-icd-git` through pacman and let ffmpeg try to autodetect

**Comment by lars18th** [comment]
> You could try to install `mingw-w64-x86_64-opencl-icd-git` through pacman and let ffmpeg try to autodetect

Hi @1480c1 ,

I don't know how to do this... Any guide?
And sorry for this stupid question.

**Comment by 1480c1** [comment]
There is some of the information in the [wiki](https://github.com/jb-alvarado/media-autobuild_suite/wiki), although I do think it needs some polishing.

mintty
===
Refers to the terminal shell that msys2 usually uses. A shortcut to running mintty can be found in the root folder of the suite `mintty.lnk`. Whenever anyone says to `run a command`, with the exception of explicitly saying powershell or command prompt, you would usually type the commands into there.

bash
===
The actual shell that mintty usually uses. Can be considered a scripting language also. It's what the scripts in this suite use as an interpreter (The `#!/usr/bin/bash` at the top of the script). Other shells include zsh (What mac OS catalina is moving to), ksh, csh, busybox, Fish, et al which I will not be listing due to the amount. They mainly originate from sh.

- Although, understanding the intricacies of bash is not necessary to use it, I would at least try to learn some of the basic commands for general file manipulation and recognizing certain stuff, etc.
- `source /build/media-suite_helper.sh`: This is one command that I would recommend you to at least know of whenever we say to source the helper script. This will essentially run the script, but allow you to have the functions and variables available to you to use. (Usually, if you run it like normal, `/build/media-suite_helper.sh` without the `source` nor `.` "dot source", the functions are limited to the script only and do not get put into the current shell.
  - I personally recommend to look at the helper script and see what kinds of functions are in there. The functions are marked with `<name_of_function>() { ... }` (Note the `()` next to the name)

msys2
===
The "system" that this suite relies on. Similar to cygwin in terms of being an "emulator" for a linux environment. However, do note, there is the MSYS2 MSYS, MSYS2 MinGW 32-bit, and MSYS2 MinGW 64-bit and they refer to different environments. The plain msys one, refers to the one that closely emulates a linux shell, meaning that most of the times, programs compiled in msys are not available outside of the the msys shell, this is the one closes to cygwin. The MinGW ones refer to a shell that mainly uses the MinGW-w64 toolchain (gcc, make, etc).

- If running bash outside of mintty (in command prompt or powershell for example), they can be chosen by setting the environment variable `MSYSTEM`
- I would recommend to just use the MinGW 64-bit environment at all times to never confuse yourself.
- Note: MinGW-w64 and msys2 are separate projects. MinGW-w64 refers to the toolchain including gcc, make, etc that has been adjusted to run on windows and produce native windows binary (Meaning they show up as `.exe` and can run through the command prompt or powershell without using an shell like bash). msys2 refers to the project that acts as a distributor of packages and a linux emulator. Although msys2 does distribute MinGW-w64 toolchain and is considered the easiest way to get it and keep updated.

pacman
===
The package manager that msys2 uses. Also present prominently in arch linux. Similar to apt and apt-get or dnf and yum (If you know about theses) in functionality, but not as "robust" with the safety of installing and removing packages (Debatable, I personally find it to be fine).

For package names, having no prefix usually means that it is msys2 related. Generally speaking, this would mean that it can only be run through bash or the mintty shell (like mercurial), although there are exceptions with packages that can be run anywhere (bash, make, tar, etc. Just look through the `msys64\usr\bin` folder in the suite and see what has `.exe` appended to them. Some of the files that don't have `.exe` are just shortcuts or aliases to others some times). Having the prefix `mingw-w64` means that it's been compiled using the MinGW toolchain, with the `x86_64` referring to a 64-bit version and `i686` referring to a 32-bit version. This just means that it's been compile specifically for use outside of bash etc.

- I would always recommend using the 64-bit version and almost never installing the 32-bit version

**Common commands:**

- `pacman -S <pkg-name[s]>`: install package from msys2's repository.
  - `pacman -S mingw-w64-x86_64-opencl-icd-git`
- `pacman -Syu`: update the package repository database and upgrade any available packages
  - `pacman -Syyuu`: force update the database and allow upgrades and downgrades (In case a version is found to be unstable/corrupt/or even just buggy)
- `pacman -Ss <pkg-name[s]>`: search for a package in the msys2 repository.
  - Alternativly, if you really are that lazy/just want to see the source. <https://github.com/msys2/MINGW-packages> and <https://github.com/msys2/MSYS2-packages>

For others commands, I would recommend you to look at the arch linux wiki for [pacman](https://wiki.archlinux.org/index.php/Pacman/Rosetta)

**Comment by 1480c1** [comment]
Open mintty, `pacman -S mingw-w64-x86_64-opencl-icd-git`, add `--enable-opencl` to ffmpeg_options.txt

**Comment by 1480c1** [comment]
Haven't tested

**Comment by wiiaboo** [comment]
The suite uses the system's OpenCL.dll directly. There's no need to compile the icd-loader ourselves.

**Comment by lars18th** [comment]
> The suite uses the system's OpenCL.dll directly. There's no need to compile the icd-loader ourselves.

Hi @wiiaboo ,

Please explain this!

- I requested about this issue because the resulting ffmpeg.exe compiled with the suite *doesn't* include OpenCL support.
- Futhermore, the runtime of the OpenCL.dll is included in recent nvidia drivers.

So, the question is quite simple: What we need to do to obtain a ffmpeg.exe binary with OpenCL enabled.

Thank you!

**Comment by lars18th** [comment]
Hi,

If I compile with `FFMPEG_OPTS+=(--enable-cuda --enable-cuda-nvcc --enable-opencl)` inside the `ffmpeg_extra.sh` I get this error after the configuration phase of the FFMPEG:
```
This is required for other packages, so this script will exit.

Attach C:\Users\user\ffmpeg-build\media-autobuild_suite\build\logs.zip to the GitHub issue.
Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
Try running the build again at a later time.
```

So, something more it's required to compile with OpenCL support.
Any idea?

**Comment by hydra3333** [comment]
Well, this person cross-compiles it OK.
https://github.com/DeadSix27/python_cross_compile_script

Maybe there's hints to be had over there.

**Comment by lars18th** [comment]
> Well, this person cross-compiles it OK.
> https://github.com/DeadSix27/python_cross_compile_script
> 
> Maybe there's hints to be had over there.

Hi @hydra3333 ,

After reading your post at https://github.com/DeadSix27/python_cross_compile_script/issues/29
I feel you can help to enable support for OpenCL with this suite.
Please comment about:
- To compile ffmpeg with OpenCL enabled, it's required to use the OpenCL-ICD-Loader package, or a simple patch with some definitions it's sufficient?

Thank you all for your support.

**Comment by wiiaboo** [comment]
> 
> 
> Hi,
> 
> If I compile with `FFMPEG_OPTS+=(--enable-cuda --enable-cuda-nvcc --enable-opencl)` inside the `ffmpeg_extra.sh` I get this error after the configuration phase of the FFMPEG:
> 
> ```
> This is required for other packages, so this script will exit.
> 
> Attach C:\Users\user\ffmpeg-build\media-autobuild_suite\build\logs.zip to the GitHub issue.
> Make sure the suite is up-to-date before reporting an issue. It might've been fixed already.
> Try running the build again at a later time.
> ```
> 
> So, something more it's required to compile with OpenCL support.
> Any idea?

That says absolutely fucking nothing. A more useless message could not have been posted. You neither uploaded the logs.zip nor pasted the whole failing message, nor even a fucking screenshot.

**Comment by hydra3333** [comment]
> Please comment

May I suggest reviewing that individual's script (which works), in particular parts for 
- building the icd OpenCL-Headers
- building the icd Loader
- the build parameters for ffmpeg when building with ICD

Although - I am reasonably sure MABS (this git) has been reliable for a really long time for a lot of people, and is very well maintained and curated.  Do the things wiiaboo  suggests and you'll do better :)

**Comment by lars18th** [comment]
Hi,

@hydra3333 ,

I agree with you. It would be useful to review this similar project. And I'm sure it can help.
However, I still have one unanswered question:

- What is required to compile ffmpeg with OpenCL enabled?

I'm sorry if this sounds a little weird. But, I'm not sure about _what needs to be compiled **externally**_. I know that it requires some headers, but it requires some binary libs?

@wiiaboo ,

I'm sorry if you found my post irritating or improperly made. I apologize. :sob: 

My objective isn't to point a bug in the suite. So for this reason I don't share the logs. They're irrelevant for this issue. The question is: Can this suite compile the ffmpeg with OpenCL enabled? If yes, what we need to do? If not, it's possible to add this support?

I hope someone can help illuminating this issue.
Regards.

**Comment by 1480c1** [comment]
Ffmpeg with opencl will automatically be compiled if your drivers has support for it (opencl.dll from your driver)

**Comment by hydra3333** [comment]
Yes, MABS does it.  Here's the relevant extract from the MABS script
```
syspath=$(cygpath -S)
[[ $bits = "32bit" && -d "$syspath/../SysWOW64" ]] && syspath="$syspath/../SysWOW64"
opencldll="$syspath/OpenCL.dll"
if files_exist "$LOCALDESTDIR/bin-video/OpenCL.dll"; then
    opencldll="$LOCALDESTDIR/bin-video/OpenCL.dll"
fi
if [[ $ffmpeg != "no" ]] && enabled opencl && [[ -f "$opencldll" ]]; then
    do_simple_print "${orange}FFmpeg and related apps will depend on OpenCL.dll${reset}"
    do_pacman_remove opencl-headers
    _check=(CL/cl.h)
    if do_vcs "https://github.com/KhronosGroup/OpenCL-Headers.git"; then
        do_uninstall include/CL
        do_install CL/*.h include/CL/
        do_checkIfExist
    fi
    _check=(libOpenCL.a)
    if test_newer installed "$opencldll" "${_check[@]}"; then
        cd_safe "$LOCALBUILDDIR"
        [[ -d opencl ]] && rm -rf opencl
        mkdir -p opencl && cd_safe opencl
        create_build_dir
        gendef "$opencldll" >/dev/null 2>&1
        [[ -f OpenCL.def ]] && dlltool -y libOpenCL.a -d OpenCL.def -k -A
        [[ -f libOpenCL.a ]] && do_install libOpenCL.a
        do_checkIfExist
    fi
else
    do_removeOption --enable-opencl
fi
unset syspath opencldll
```

From another place, here's an extract of something done similar to deadsix27's  (it's in json form). It works.
```
	'ffmpeg_static_opencl' : {
		'repo_type' : 'git',
		'url' : 'git://git.ffmpeg.org/ffmpeg.git',
		'rename_folder' : 'ffmpeg_static_opencl_git',
		'configure_options': '!VAR(ffmpeg_base_config)VAR! --enable-libbluray --prefix={product_prefix}/ffmpeg_static_opencl_git.installed --disable-shared --enable-static --enable-opencl --extra-cflags="-DLIBXML_STATIC" --extra-cflags="-DGLIB_STATIC_COMPILATION" ', # 2018.11.23 added 2x extra-cflags
		'depends_on': [ 'ffmpeg_depends', 'opencl_icd' ],
		'_info' : { 'version' : 'git (master)', 'fancy_name' : 'ffmpeg (static (OpenCL))' },
	},
	'ffmpeg_depends' : { # this is fake dependency used to just inherit other dependencies, you could make other programs depend on this and have a smaller config for example.
		'is_dep_inheriter' : True,
		'depends_on' : [
			'iconv', 'gettext',
			'zlib', 'bzip2', 'xz', 'libzimg', 'libsnappy', 'libpng', 'gmp', 'libnettle', 'gnutls', 'frei0r', 'libsndfile', 'libbs2b', 'wavpack',
			'libgme_game_music_emu', 'libwebp', 'flite', 'libgsm', 'sdl2', 'libopus', 'opencore-amr', 'vo-amrwbenc', 'libogg', 'libspeex', 'davs2', 'openmpt',
			'libvorbis', 'libtheora', 'freetype', 'expat', 'libxml2', 'libbluray', 'libxvid', 'xavs', 'xavs2', 'libsoxr', 'libx265_multibit', 'libaom', 
			'libdav1d',  # 2019.05.10 undo disable # 2019.05.10 undo disable # 2019.03.12 disable
			'vamp_plugin', 'fftw3', 'libsamplerate', 'librubberband', 'liblame' ,'twolame', 'vidstab', 'libmysofa', 'libcaca', 'libmodplug',
			'zvbi', 'libvpx', 'libilbc', 'libfribidi', 'libass', 'intel_quicksync_mfx', 'rtmpdump', 'libx264', 'libcdio', 'libcdio-paranoia', 'amf_headers', 'nv-codec-headers',
			'vapoursynth_libs', # 2018.11.23 include vapoursynth_libs
			'libgcrypt', # 2018.11.28
			'libsrt', # 2019.05.10
			#'liblensfun', 'libtesseract', # 2018.12.05
		],
	},

	'opencl_icd' : {
		'repo_type' : 'git',
		'url' : 'https://github.com/KhronosGroup/OpenCL-ICD-Loader.git',
		#'branch' : '467f28628fbca25f334c56422a4bfe116912bb22', # 2019.07.17
		'needs_make_install' : False,
		'conf_system' : 'cmake',
		'configure_options': '. {cmake_prefix_options} -DCMAKE_INSTALL_PREFIX={target_prefix} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DOPENCL_ICD_LOADER_REQUIRE_WDK=false', # was -DBUILD_SHARED_LIBS=OFF
		# -DBUILD_SHARED_LIBS=ON due to explanation here https://github.com/DeadSix27/python_cross_compile_script/commit/0218b4b80830563c7aab2b1e6d561d20977f5fd4#commitcomment-33472895
		# i.e. Shared means it will use the system provided opencl.dll, which is supplied by AMD or Intel for example. (the right way). Needed, to create the .dll.a file.
		'depends_on' : [ 'opencl_headers' ],
		#'run_post_patch' : [
		#	'sed -i.bak \'s/Devpkey.h/devpkey.h/\' icd_windows_hkr.c',
		#],
		'run_post_build' : [
			#'if [ ! -f "already_ran_make_install" ] ; then cp -fv "libOpenCL.dll.a" "{target_prefix}/lib/libOpenCL.dll.a" ; fi',
			'cp -fv "libOpenCL.dll.a" "{target_prefix}/lib/libOpenCL.dll.a"',
			'if [ ! -f "already_ran_make_install" ] ; then touch already_ran_make_install ; fi',
		],
		'patches' : [
			#('https://raw.githubusercontent.com/hydra3333/h3333_python_cross_compile_script_v02/master/patches/opencl/0001-OpenCL-git-prefix.patch','-p1'),
			('https://raw.githubusercontent.com/hydra3333/h3333_python_cross_compile_script_v02/master/patches/opencl/0001-OpenCL-git-prefix-2019.05.09.patch','-p1'),
			#('https://raw.githubusercontent.com/hydra3333/h3333_python_cross_compile_script_v02/master/patches/opencl/0002-OpenCL-git-header.patch','-p1'),
			('https://raw.githubusercontent.com/hydra3333/h3333_python_cross_compile_script_v02/master/patches/opencl/0002-OpenCL-git-header-2019.05.09.patch','-p1'),
		],
		'run_post_patch' : [
			'sed -i.bak \'s/Windows.h/windows.h/\' loader/windows/icd_windows_envvars.c',
		],
		'depends_on' : [ 'opencl_headers' ],
		'_info' : { 'version' : 'git (master)', 'fancy_name' : 'OpenCL-ICD-Loader' },
	},
	'opencl_headers' : {
		'repo_type' : 'git',
		'url' : 'https://github.com/KhronosGroup/OpenCL-Headers.git',
		'run_post_patch' : (
			#'if [ ! -f "already_ran_make_install" ] ; then if [ ! -d "{target_prefix}/include/CL" ] ; then mkdir -pv "{target_prefix}/include/CL" ; fi ; fi',
			#'if [ ! -f "already_ran_make_install" ] ; then cp -rfv CL/*.h "{target_prefix}/include/CL/" ; fi',
			#'if [ ! -f "already_ran_make_install" ] ; then touch already_ran_make_install ; fi',
			'if [ ! -d "{target_prefix}/include/CL" ] ; then mkdir -pv "{target_prefix}/include/CL" ; fi',
			'cp -rfv CL/*.h "{target_prefix}/include/CL/"',
			'touch already_ran_make_install',
		),
		'needs_make':False,
		'needs_make_install':False,
		'needs_configure':False,
		'_info' : { 'version' : 'git (master)', 'fancy_name' : 'OpenCL-Headers' },
	},
```

**Comment by hydra3333** [comment]
Also - notice that MABS (which runs under Windows) is different to the other cross-compiling stuff.  

MABS uses the external file OpenCL.DLL which is installed by your graphics card driver install process and combines that with the OpenCL headers which it downloads, to be used in the building process.

The other uses the OpenCL headers which it downloads together with the OpenCL_ICD repository to build an equivalent libOpenCL.dll.a, to be used in its building process.

Hope that helps.

**Comment by lars18th** [comment]
> Ffmpeg with opencl will automatically be compiled if your drivers has support for it (opencl.dll from your driver)

Thank you @wiiaboo ! :+1: 
That's the answer I've been looking for.
So I do a full clean install of the suite, reconfigured it, and now the OpenCL support is included by default. :hugs: 

Regards.

**Comment by foroughmajidi** [comment]
I want to build FFmpeg with opencl but do not know how to start.
Can anyone help me do the task step by step?

**Comment by 1480c1** [comment]
Have you tried reading the whole issue?

**Comment by hydra3333** [comment]
I tried it tonight, using a free Microsoft Development Environment hyperV VM, https://developer.microsoft.com/en-us/windows/downloads/virtual-machines/ which did not have any nvidia or good driver with OpenCL installed.

I tried Two ways:  
1. It seemed to build automatically if I first installed the nvidia SDK per https://github.com/m-ab-s/media-autobuild_suite#notes-about-cuda-sdk however you then ended up with a dependency on other nvidia CUDA external dll's (and, for the moment, openh264.dll unless you disable building that in ffmepg_options)  
2. by lightly modding the compile code to ONLY look for a local copy of OpenCL.dll which I had copied from a system with an nvidia driver installed.  It threw some include errors in the build so I then had to add a copying of headers to another lib subfolder OpenCL.  But then the ffmpeg build always threw an error saying OpenCL not found so I must be doing something wrong.    

Gave up just about then and went back to an old cross-compile script which downloaded OpenCL_icl_loader (which has just recently been updated with an extra -D build flag to create an import lib only).

Having said that, MABS is a GREAT project !!

Good luck.

**Comment by foroughmajidi** [comment]
I get https://github.com/FFmpeg/FFmpeg.git and I think I should continue in the following way;

./configure --arch=x64
--pkg-config=pkg-config --enable-gpl --enable-libx264 --enable-avisynth
 --enable-libxvid --enable-libmp3lame --enable-version3 --enable-zlib
 --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex
 --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype
 --enable-libopus --disable-w32threads --enable-frei0r
 --enable-filter=frei0r --enable-libvo-aacenc --enable-bzlib
 --enable-libxavs --extra-cflags=-DPTW32_STATIC_LIB
 --enable-libopencore-amrnb --enable-libopencore-amrwb
 --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx
 --enable-libilbc --enable-iconv --enable-libtwolame --enable-opencl
 --extra-cflags=-DLIBTWOLAME_STATIC --enable-libmodplug
 --extra-libs=-lstdc++ --enable-libzvbi --enable-libcaca

Seems I don't have any OpenCL SDK installed.
There are different SDK from different providers:
NVIDIA – CUDA Toolkit
AMD – AMD APP SDK
Intel - OpenCL SDK

However I don't know which one is the right choice to choose?
Are the mentioned steps correct ? or additional works should be done?
My main aim is to build it on windows 10 (platformx64).
Is it possible to do it by mingw64?

**Comment by 1480c1** [comment]
First of all, what gpu do you have? Nvidia, AMD, or Intel integrated?

**Comment by foroughmajidi** [comment]
![Capture45](https://user-images.githubusercontent.com/51900859/81479399-cbb73880-91d7-11ea-9e33-72c128b4ace0.PNG)

![Capture46](https://user-images.githubusercontent.com/51900859/81479409-d7a2fa80-91d7-11ea-89aa-6a5518024571.PNG)


![Capture47](https://user-images.githubusercontent.com/51900859/81479413-de317200-91d7-11ea-94de-be5edb75bbfe.PNG)
 This is my system informations

**Comment by 1480c1** [comment]
Install nvidia's drivers, then make sure your ffmpeg_options.txt has `--enable-opencl` or choose ffmpeg full

**Comment by foroughmajidi** [comment]
You mean I need NVIDIA – CUDA Toolkit sdk?
I want to use FFmpeg  in a project in case somebody uses this project and her/his system deosn't have gpu use cpu.  Do I need to install drivers?

**Comment by 1480c1** [comment]
no, the suite searches from `C:/Windows/SysWOW64/OpenCL.dll` or `C:/Windows/System32/OpenCL.dll`, as long as you've installed your graphics drivers and your drivers and gpu supports opencl, it should work

**Comment by 1480c1** [comment]
If you do not want to build it yourself, you can get some binaries from https://jeremylee.sh/bin.html, it includes opencl

**Comment by foroughmajidi** [comment]
Thank you for your guidance
So at first I should install nvidia's drivers then ./configure --arch=x64 --enable-opencl( I check in configure file,it  has --enable-opencl          enable OpenCL processing [no]) 
Are the mentioned steps correct ? or additional works should be done?

**Comment by 1480c1** [comment]
Sure, however, anything outside of the suite is not covered by the suite. If it fails, you are on your own, try taking it to another forum

**Comment by foroughmajidi** [comment]
Thanks

**Comment by hydra3333** [comment]
PS just a thought, you aren't going to receive miracles from graphics cards: 720m nor a 4000 ;)

**Comment by foroughmajidi** [comment]
On my system  nvidia drivers is installed and I installed mingw-w64-x86_64-opencl-icd-git  
and I built FFmpeg as following:
1-x86-x64 cross tools command prompt for VS 2019 run as administrator and run mingw64 in it 
2-cd c:\ffmpeg_test\ffmpeg
3-./configure --enable-opencl 
But opencl not found 
I export Path of "cl"  and opencl.dll is in c:\windows\system32
Would you mind telling me how to solve it?

**Comment by foroughmajidi** [comment]
![Capture1](https://user-images.githubusercontent.com/51900859/81779051-2ff43800-9509-11ea-87ef-b15fd52f34a7.PNG)

![Capture2](https://user-images.githubusercontent.com/51900859/81779074-3b476380-9509-11ea-943e-1276b4b8a8ea.PNG)

**Comment by hydra3333** [comment]
A thought on building ffmpeg with OpenCL.

MABS may be "better off" to reliably download and use the new updated  KHRONOS OpenCL-ICD-Loader https://github.com/KhronosGroup/OpenCL-ICD-Loader.git  and OpenCL-Headers headers https://github.com/KhronosGroup/OpenCL-Headers.git.

The ICD Loader has just recently been updated with an extra build flag `-DOPENCL_ICD_LOADER_DISABLE_OPENCLON12=ON`  to create an import lib only, and build against that.

eg

1. install OpenCL headers
after the git clone of `https://github.com/KhronosGroup/OpenCL-Headers.git` and cd into it, do
mkdir -pv "{target_prefix}/include/CL" 
cp -rfv CL/*.h "{target_prefix}/include/CL/"
where {target_prefix} is the MABS folder under which "include" folder resides alongside the "lib" folder.

2. build the ICD Loader
clone `https://github.com/KhronosGroup/OpenCL-ICD-Loader.git` and cd into it
Apply these 2 patches
https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/opencl/0001-OpenCL-git-prefix.patch
https://raw.githubusercontent.com/DeadSix27/python_cross_compile_script/master/patches/opencl/0002-OpenCL-git-header.patch
Build with cmake example only, *use the MABS cmake commandline instead of this example*
`cmake . -DCMAKE_TOOLCHAIN_FILE="/_working/workdir/mingw_toolchain.cmake" -G"Ninja" -DCMAKE_INSTALL_PREFIX={target_prefix} -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DOPENCL_ICD_LOADER_REQUIRE_WDK=OFF -DOPENCL_ICD_LOADER_DISABLE_OPENCLON12=ON`  
where {target_prefix} is the MABS folder under which "include" folder resides alongside the "lib" folder.

3. after build, copy the .dll.a to .a
cp -vf "{target_prefix}/lib/libOpenCL.dll.a" "{target_prefix}/lib/libOpenCL.a"
where {target_prefix} is the MABS folder under which "include" folder resides alongside the "lib" folder.

**Comment by foroughmajidi** [comment]
What do you mean "where {target_prefix} is the MABS folder under which "include" folder resides alongside the "lib" folder."?
I done it as following:
![Capture3](https://user-images.githubusercontent.com/51900859/81788039-2671cc80-9517-11ea-905d-e151516cebcc.PNG)

Is it correct?
Thanks

**Comment by hydra3333** [comment]
I do not reckon so. 
It needs to be in exactly the right place in the "system include" area so that the build process can find it. 

Since this is all about MABS, look in the MABS on how/where they put it.
eg in https://github.com/m-ab-s/media-autobuild_suite/blob/master/build/media-suite_compile.sh in the vapoursynth portion.

Run MABS and look in the folder tree for where include and lib reside.

Other than that, it's now up to you as this is the MABS issues area.

**Comment by foroughmajidi** [comment]
I want to  build ffmpeg alone not in a MABS .
I built it in  cygwin with opencl and it was ok but when I built it with msvc it didn't found opencl

**Comment by hydra3333** [comment]
OK, good luck to you.

**Comment by foroughmajidi** [comment]
I have done above steps and I can not find any solution for building ffmpeg,
Would you please help me how with with the problem(opencl not found)?

**Comment by hydra3333** [comment]
Sorry I'm not cygwin-aware.
Perhaps ask on one of these forums which can be more general in nature:

https://ffmpeg.zeranoe.com/forum/viewforum.php?f=5&sid=ef550f32109a8434c0c06766bac29ef0

https://forum.videohelp.com/forums/38-Programming

https://github.com/rdp/ffmpeg-windows-build-helpers/issues (this place builds it)

http://forum.doom9.org/forumdisplay.php?f=41

good luck

**Comment by foroughmajidi** [comment]
Thank you ,now I decide use MABS ,In addition of .exe I want .dll ,Can I add --enable-shared in ffmpeg_option.txt?My boss wanted me to build ffmpeg with vc++.but I get opencl not found.

    On Saturday, May 16, 2020, 03:13:09 PM GMT+4:30, hydra3333 <notifications@github.com> wrote:  
 
 


Sorry I'm not cygwin-aware.
Perhaps ask on one of these forums which can be more general in nature:

https://ffmpeg.zeranoe.com/forum/viewforum.php?f=5&sid=ef550f32109a8434c0c06766bac29ef0

https://forum.videohelp.com/forums/38-Programming

https://github.com/rdp/ffmpeg-windows-build-helpers/issues (this place builds it)

http://forum.doom9.org/forumdisplay.php?f=41

good luck

**Comment by hydra3333** [comment]
The OpenCL.dll ?  Why ?  I suggest you likely do not want to create a .dll.

The flag -DOPENCL_ICD_LOADER_DISABLE_OPENCLON12=ON will not make a useable .dll anyway, it will make an "import lib" .a file.

The whole point of building ffmpeg.exe with the OpenCL import lib you create via the ICD Loader, is that on your Windows x64 System the graphics device driver (eg nvidia) installation provides the correct fully functional OpeCL.dll which ffmpeg.exe automatically loads at runtime.  You do not want to overwrite that !

**Comment by hydra3333** [comment]
PS I'm sure you could build with vc.  

Perhaps try asking about it on the ffmpeg-users or ffmpeg-devel list (remember to not "top-post")

https://ffmpeg.org/mailman/listinfo/ffmpeg-devel

**Comment by hydra3333** [comment]
PPS ... licensing may or may not apply depending on what you are doing, some dependencies are non-free and require licenses in certain circumstances ... (you mentioned "My boss wanted me to build ffmpeg with vc++").

**Comment by foroughmajidi** [comment]
I think my explanation was not clear.About  dll ,I meant  libavacodec.dll, libavdevice.dll, libavfilter.dll,.. after building FFmpeg.I sent an email to this address:ffmpeg-devel@ffmpeg.org. but no one replied.
It is of my great chance that you answer me very well.best regards.
    On Saturday, May 16, 2020, 07:07:10 PM GMT+4:30, hydra3333 <notifications@github.com> wrote:  
 
 


The OpenCL.dll ? Why ? I suggest you likely do not want to create a .dll.

The flag -DOPENCL_ICD_LOADER_DISABLE_OPENCLON12=ON will not make a useable .dll anyway, it will make an "import lib" .a file.

The whole point of building ffmpeg.exe with the OpenCL import lib you create via the ICD Loader, is that on your Windows x64 System the graphics device driver (eg nvidia) installation provides the correct fully functional OpeCL.dll which ffmpeg.exe automatically loads at runtime. You do not want to overwrite that !

**Comment by 1480c1** [comment]
https://lists.ffmpeg.org/mailman/listinfo/ffmpeg-user/

**Comment by 1480c1** [comment]
ffmpeg-devel is not the place to go with questions on compiling etc, that list is supposed to be for developers and submitting commits, ffmpeg-user is the more suitable list for you to post on.

You have to signup for the list

**Comment by 1480c1** [comment]
Locking this issue since this is not a general FFmpeg help forum, this page is supposed to be specifically for media-autobuild_suite issue and questions, please try one of the links @hydra3333 posted and try getting help from there (Although maybe not the ffmpeg-windows-build-helpers since they also use mingw-w64 and not msvc nor cygwin)
