### ISSUE TITLE
Add HE-AAC+ v2 encoder in "non-free" compilation

### ISSUE THREAD

**Issue by silverkorn** [jb-alvarado/media-autobuild_suite#136]
For details:
- https://trac.ffmpeg.org/wiki/How%20to%20quickly%20compile%20libaacplus
- http://tipok.org.ua/node/17

Thanks!

**Comment by wiiaboo** [comment]
Non-free fdk-aac already supports he-aac v2, is probably higher quality and apparently libaacplus conflicts with other encoders inside ffmpeg in some way.

There any reason in particular to include libaacplus besides just because it's yet another aac encoder?

Unless you make a PR and made sure it works well with ffmpeg, mplayer and mpv 32 and 64-bit I don't really care about adding another old aac encoder. Maybe @jb-alvarado does.

**Comment by silverkorn** [comment]
You're right, nevermind;
I forgot to use the `-profile:a aac_he_v2` argument :S

My bads!
