### ISSUE TITLE
A question about media-suite_compile.sh

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#161]
Not an issue, this time, just a 2 questions:
1. in "media-suite_compile.sh" 
sed -ri  "s/ ?--(target-os|prefix|bindir|extra-(cflags|libs))=(\S+|'[^']+')//g" config.h   
What stands the backquoted S (\S) for ? Spaces ? A selection ?
You don't gave to explain extended regular expressions,  just what \S+ is.

2. Concerning the MSys updates I mentioned earlier (these that broke D3D11 ...)
I reinstalled the older files (see my previous post)  and DXVA/D3D11 is back in ffmpeg.
How can I prevent that the updated are reinstalled when I update ?
How to make some kind of a blacklist for these updates ?

Thanks for your answer !

**Comment by wiiaboo** [comment]
>What stands the backquoted S (\S) for ? Spaces ? A selection ?
You don't gave to explain extended regular expressions, just what \S+ is.

\S is the same as [^\s], which is the same as [\w], or "any character that's not whitespace".

> How to make some kind of a blacklist for these updates ?

See /etc/pacman.conf and add the relevant packages to (I think) IgnorePkg. But if you run `pacman -S <package>` it will still try to update it, since you're being explicit.
You can update the packages now anyway. Only thing that's missing is D3D11VA. DXVA2 works fine and is what mpv and lavfilters use. D3D11VA is basically the same of DXVA2 afaik.

**Comment by pat357** [comment]
so [^ ]+ (1 or more no spaces)  and [^ ][^ ]is the same as /S+ ?
It means 1 or more not spaces ?

**Comment by pat357** [comment]
The 2nd one  should be [^ ][^ ]*  . (with a * behind)

**Comment by wiiaboo** [comment]
Yes.
`+` for one or more, `*`  for zero or more, `?` for zero or one.
To use `+` without escaping you need `-r` option in sed.

**Comment by pat357** [comment]
The rest of the ERE:  |'[^']+')//g
Where comes the | out ?
Is "|" just a literal or has it maybe also another meaning... ?
I see no matches for | or am I missing something ?

**Comment by pat357** [comment]
Do you maybe have a good url about Extended RE's ?

**Comment by pat357** [comment]
Now I see it : (...a...| ...b..) :+1: 
means a or b .
I got it now ;-)

**Comment by wiiaboo** [comment]
`|` separates an alternative match
You can test and learn about regex in many sites. I use http://www.regexr.com/ and https://regex101.com/
