### ISSUE TITLE
Build fails in ffmpeg with libkvazaar

### ISSUE THREAD

**Issue by nille02** [jb-alvarado/media-autobuild_suite#173]
INSTALL doc/libavfilter.3
CC      ffmpeg.o
AR      libavdevice/libavdevice.a
AR      libavfilter/libavfilter.a
AR      libavformat/libavformat.a
CC      libavcodec/libkvazaar.o
libavcodec/libkvazaar.c: In function 'libkvazaar_encode':
libavcodec/libkvazaar.c:176:10: error: too few arguments to function 'ctx->api->encoder_encode'
     if (!ctx->api->encoder_encode(ctx->encoder, img_in, &data_out, &len_out, NULL)) {
          ^
libavcodec/libkvazaar.c:186:9: warning: 'ff_alloc_packet' is deprecated [-Wdeprecated-declarations]
         retval = ff_alloc_packet(avpkt, len_out);
         ^
In file included from libavcodec/libkvazaar.c:30:0:
libavcodec/internal.h:225:26: note: declared here
 attribute_deprecated int ff_alloc_packet(AVPacket *avpkt, int size);
                          ^
common.mak:57: die Regel für Ziel „libavcodec/libkvazaar.o“ scheiterte
make: *** [libavcodec/libkvazaar.o] Fehler 1
-------------------------------------------------
Build of ffmpeg-git failed...
Delete the source folder under '/build' and start again.
If you're sure there are no dependencies <Enter> to continue building.
Close this window if you wish to stop building.

I deleted both in the build folder and run 2 times in the error.

**Comment by wiiaboo** [comment]
I think there's a problem with libkvazaar and ffmpeg since recent commits. There's a patch in FFmpeg's mailing list, so it'll be fixed soon. In the meantime, wait or comment (add a # before) "--enable-libkvazaar" in ffmpeg_options.txt, or use 4204b86323a3dc1d3373fd38a99621b05f710116 which sticks to an older kvazaar commit that probably works (didn't test).
