### ISSUE TITLE
A few things that look "suspected"...

### ISSUE THREAD

**Issue by pat357** [jb-alvarado/media-autobuild_suite#174]
Hi all,
I noticed a few "anomalies" in the compile script, one more imported than the other:
1. About the new 'do_x265_cmake' function.
Line 1108 : build_x265
At this moment the  'do_x265_cmake' function is a nested function inside 'build_x265", what means that 'build_265 will also compile and install.
Line 1109 is not needed, but then where is for example the numa version installed  ?
I think a small change is needed.

2. LibFAAC : existing installation (libfaac.a in lib and .h in include are not deleted when compiling)

3. Some packages have no proper clean install : libILBC ,libfdk-aac, fdkaac.exe, sox.exe, 
  They have the same problem that libASS had (solved a while ago).
   The problem these have is that the after deleting the directory in build, the existing installation in not deleted before compiling

4.Gpac :  line 692
You delete something like $LOCALDESTDIR/bin-video/gpac ...I guess this should be $LOCALDESTDIR/bin-video/MP4Box.exe  .. no ?

5.Our C-flags specify  '-O2 -mtune=generic'
O2 : what optimization is used when the package adds -O3 too the flags ? Our -O2 or the -O3 ?
(IIRC x264 and x265 are supposed to be compiled with -03, they add -O3 too the flags.
I would expect the compiler will use the lowest O  if more than 1 is provided, this way the user can still compile these packages with O2 when O3 gives problems..

-mtune=generic : why not use -mtune=NATIVE ?
Most users don't distribute their files, I guess (also illegal due non-free libs used}
mtune=native is the best setting for their system I think... agreed ?

6. In the update.sh (media-suite_update.sh):
In function  check_profiles:
To remove all the echo. from the .bat you use : sed "s/\s*echo.//g"
I suspect this doesn't do what you think as it removes also a real echo in my profiles:
something like   ' echo.echo "my text" '
What you mean is likely this sed "s/\s*echo[.]//g" or sed "s/\s*echo.//
The . (dot) in the your expression means ANY character, if you want a dot as a literal ,you have to place it between square brackets like [.].
Another solution is to get rid of the 'g' : do you really expect more then one echo. per line ? :-)
So both sed "s/\s*echo[.]//g"   and   sed "s/\s*echo.//  work.

7. This is more a question
I want to create a function to retrieve the package name with only ${PWD} as input
Currently I use this:

give_packagename() {
local packetname=""
local PWD_=${PWD#*/build/}
if $(echo ${PWD} | grep -q -E -e '.*-(git|hg|svn)' -) ; then
            packetname=$(echo ${PWD} | sed -e 's|/|\n|g' | grep -E -e '.*-(git|hg|svn)$' -)
elif  [[ ${PWD_##*/} = build ]]; then
            packetname=${PWD_%/*}
            packetname=${packetname##*/}
else
            packetname=$(echo ${PWD_} | sed -e 's|/|\n|g' | head -1)        
fi
packetname=${packetname%-*}
}

This works as far as I've tested, but it looks to complicated for a relative simple task.
Just my PWD_ (  = ${PWD#*/build/} )  gives the packetname in front like:
' vpx-git/dir1/dir2  '.
I just can't find a way to remove the trailing dirs
 packetname=${PWD_%%/*} should work because there is no leading / before ' vpx-git/dir1/dir2 ' , but it still deletes everything. (probably it assumes the input always starts with / ??)
I have tried with ERE but it seems to be limited to RE's  (no extended)
Anyway I couldn't make it work with something like  ${PWD_%%\([^/][^/]*\)/*
  matching everything but working with /(.. /) around the part you want to delete/keep

I would really appreciate if you would share your expertise in this matter to help me to make a simple & 
robust function for this.
Also tried with EXPR , but could not make ik work

**Comment by pat357** [comment]
Strange, when I copy/paste text/code from my editor to this window, some ' * ' are deleted.
Sorry for that. Also the list numbers are messed up.

About the update.sh the correct way to remove the leading 'echo.' on every line is
sed "s/\s*echo[.]//g"  or  sed "s/\s*echo.//  or sed "s/\s*echo[.]//
IMO the 3rd is a more logical choice : echo. should be removed only once per line and the trailing . in echo.is correctly matched by the brackets.

**Comment by wiiaboo** [comment]
>1. About the new 'do_x265_cmake' function.
Line 1108 : build_x265
At this moment the 'do_x265_cmake' function is a nested function inside 'build_x265", what means that 'build_265 will also compile and install.
Line 1109 is not needed, but then where is for example the numa version installed ?
I think a small change is needed.

I don't think I understand the problem. `ninja install` is run after `build_x265`.
`do_x265_make` only runs `ninja` without installing.
`build_x265` must be run inside `do_x265_make` because we change "xpsupport" value before running the numa version.

-
> LibFAAC : existing installation (libfaac.a in lib and .h in include are not deleted when compiling)

I never compiled faac, so I didn't write an uninstall.

-
> 5.Our C-flags specify '-O2 -mtune=generic'
O2 : what optimization is used when the package adds -O3 too the flags ? Our -O2 or the -O3 ?
(IIRC x264 and x265 are supposed to be compiled with -03, they add -O3 too the flags.
I would expect the compiler will use the lowest O if more than 1 is provided, this way the user can still compile these packages with O2 when O3 gives problems..

No idea.

-
> -mtune=generic : why not use -mtune=NATIVE ?
Most users don't distribute their files, I guess (also illegal due non-free libs used}
mtune=native is the best setting for their system I think... agreed ?

Differences should be negligible and turns binaries incompatible with other architectures if native is used, so I vote for no.

-
> In the update.sh (media-suite_update.sh):
In function check_profiles:
To remove all the echo. from the .bat you use : sed "s/\secho.//g"
I suspect this doesn't do what you think as it removes also a real echo in my profiles:
something like ' echo.echo "my text" '
What you mean is likely this sed "s/\secho[.]//g" or sed "s/\secho.//
The . (dot) in the your expression means ANY character, if you want a dot as a literal ,you have to place it between square brackets like [.].
Another solution is to get rid of the 'g' : do you really expect more then one echo. per line ? :-)
So both sed "s/\secho[.]//g" and sed "s/\s*echo.// work.

There aren't any extra echos in the bat. What do you mean? The expression can be changed to only remove windows "echo." using `^\s*echo\.` ~~but if if `/g` isn't used only one line is cleaned~~ `/g` isn't needed after all.

**Comment by wiiaboo** [comment]
In the case of x265, it seems to remove our $CFLAGS `-O2` so it uses `-O3`, since default BUILD_TYPE is Release.

In the case of x264, I'd need a recompilation to check.
According to gcc manual:
>If you use multiple -O options, with or without level numbers, the last such option is the one that is effective. 

So it probably uses our -O2.

**Comment by nille02** [comment]
> -mtune=generic : why not use -mtune=NATIVE ?
> Most users don't distribute their files, I guess (also illegal due non-free libs used}
> mtune=native is the best setting for their system I think... agreed ?

I'am distribute the files on my Systems. Its a mix of AMD and Intel CPUs.

**Comment by wiiaboo** [comment]
And I also use my binaries in other systems that aren't exactly the same as mine, so there you go.

**Comment by wiiaboo** [comment]
About packagename function, how about just `echo ${PWD} | grep -Po "[^/]+(?=-(git|hg|svn))"`?
