### ISSUE TITLE
FEATURE REQUEST: Support for CPU Arch optimizations

### ISSUE THREAD

**Issue by hekitoshinoda** [jb-alvarado/media-autobuild_suite#179]
Would it be possible to add possibillity to compile with cpu optimizations?

For example for x265: -DCMAKE_CXX_FLAGS="<b>-march=bdver3 -Ofast</b> -pipe -static-libgcc -static-libstdc++" -DCMAKE_C_FLAGS="<b>-march=bdver3 -Ofast</b> -pipe -static-libgcc -static-libstdc++"

I know this is not a script addressing the pros and will things keep simple.
Just like to ask for.

**Comment by wiiaboo** [comment]
Using https://github.com/jb-alvarado/media-autobuild_suite/commit/11ca57a4d10f52ca2d01e261031c11b8ea00b80e you can add your own CFLAGS/CXXFLAGS.
This will never be officially supported since besides making negligible performance difference it might introduce bugs by using random flags.

You can also obviously add the flags to just x265 by changing the [relevant lines](https://github.com/jb-alvarado/media-autobuild_suite/blob/38b2ce5aa34660d9a7d7132209f7a26be2ee8c44/build/media-suite_compile.sh#L1083-L1084) in `compile.sh`.

**Comment by hekitoshinoda** [comment]
Hi.
The second aproach I'd done so far in the past.
Works great.
I agree with you, for the most tools it makes not much noticable difference.
But I feel it worth to do for encoders which runs hours/days for a job to
finish.
Thanks for the hint.

2015-10-10 15:05 GMT+02:00 Ricardo Constantino <notifications@github.com>:
