### ISSUE TITLE
Despite configuring to build VPX only, many more projects were built

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#191]
I tried to configure the suite to build only VPX binaries. Still, it compiled several more, like tesseract, zimg, kvazaar (despite other265=2), libbluray, libass.

Already the early configuration logic is a bit flawed; I have to decide which license kind of ffmpeg I want to build before deciding whether to build ffmpeg at all.

**Comment by wiiaboo** [comment]
It's not flawed. The script is mostly meant for/tested for ffmpeg/mpv. I'm not going to test every single combination of options.
ffmpeg_options.txt is the source of most decisions, so use it accordingly. Create a new ffmpeg_options.txt with just
```
--enable-libvpx
--disable-sdl
```
and make sure the file is picked up (using `ffmpegUpdate=2`).
This will only compile vpx.

And the license doesn't matter just to FFmpeg. It influences rtmpdump's SSL library too, since yesterday.

**Comment by wiiaboo** [comment]
Of course, if you know of a better way to do these, you're welcome to suggest improvements/pull request.

**Comment by wiiaboo** [comment]
Latest commit should make more stuff dependant on whether ffmpeg is compiled or not.
