### ISSUE TITLE
Libaacplus support for private builds

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#201]
Would be nice if libaacplus could also be supported, see:
https://trac.ffmpeg.org/wiki/How%20to%20quickly%20compile%20libaacplus

**Comment by wiiaboo** [comment]
It's really shitty quality and non-free. Why?

**Comment by Selur** [comment]
good point, mainly thought about about it for diversity reasons. :)

**Comment by wiiaboo** [comment]
vo-aacenc is included because it's GPL-compatible, even though it's shitty. It'll probably be removed when the native AAC encoder loses experimental flag. Should be any day now. Since it's higher quality (close to fdk-aac now) and free, it obsoletes vo-aacenc completely.

Faac is included because it was a very common AAC encoder and I don't know how well mencoder works with others.

Other alternative codecs are there because they were already in the script when I started working on it. If it works already there's no work maintaining. In the case of an unmaintained library like libaacplus, which offers nothing besides being yet another AAC encoder, I really don't feel like losing time adding it and testing. If someone makes a pull request with it, sure.

**Comment by Vangelis66** [comment]
... According to a 2012 thread on the [FFmpeg-user] mailing list: 

http://ffmpeg.org/pipermail/ffmpeg-user/2012-October/010293.html

it would appear that on Windows, libaacplus and libfdk-aac are 
incompatible - of course, this may have changed since then, I haven't tested 
with a recent build, however as libfdk-aac is superior to libaacplus, 
I don't feel the need to test...
 In the last post of the referenced thread, it says: 
> libaacplus won't let FFmpeg build with libfdk-aac or libvo-aacenc.
> libaacplus lets FFmpeg build OK with libfaac though.

Just thought I should mention the above...
BTW, wiiaboo & jb-alvarado thank you very much 
for keeping this excellent project still alive, at the expense 
of a great chunk out of your personal free time...

Regards, 
Vangelis.

**Comment by wiiaboo** [comment]
I thought I remembered something like that.
It probably works with `--extra-ldflags="-Wl,--allow-multiple-definition"` or something, but yeah, I don't really care for it.
