### ISSUE TITLE
[Question] Linux equivalent

### ISSUE THREAD

**Issue by silverkorn** [jb-alvarado/media-autobuild_suite#261]
Hi!

I was wondering if there's a fork or a similar project to downlaod, configure and compile a wide set of libraries for a Linux compatible FFmpeg binary.
If not, which files/sections would need modifications to prepare the final configuration to use Linux specific flags instead of Windows/MinGW ones? Any guidelines? Removing/Adjusting all `MinGW` references in the `build/media-suite_compile.sh` script?

Thanks! :smile:

**Comment by wiiaboo** [comment]
For GNU/Linux, if the libs work, just `./configure && make && make install` would be enough for most. And in most distros, the package managers are enough for most uses.

For libs that give problems, you can follow instructions from Archlinux's PKGBUILDs in  https://www.archlinux.org/packages/ or https://aur.archlinux.org/packages/

These scripts are useful for MinGW because it's not as simple as it is for Linux/Mac.

**Comment by silverkorn** [comment]
Ok, I'll give it a try when possible!
Thanks!
