### ISSUE TITLE
build static ffmpeg release/6.1 fails

### ISSUE THREAD

**Issue by mojie126** [jb-alvarado/media-autobuild_suite#2641]
The test failed to compile on all branches except master.
The tested branches include release/6.1 and release/7.0
Tags include n7.0 and n6.1.1

[logs.zip](https://github.com/m-ab-s/media-autobuild_suite/files/14974758/logs.zip)

**Comment by L4cache** [comment]
You need a patch that was removed in https://github.com/m-ab-s/media-autobuild_suite/commit/64bf59ff7fe8fdb79769ac791403b43e06f455c6
What the patch does is just remove the `-lHLSL -lOGLCompiler` from ffmpeg `configure`.

The weird thing is, the master branch code contains those flags as well and don't make trouble.
This problem was exist in master branch too, the patch was created to solve it, but somehow the problem just vanished without any change to those flags, magically, and the patch was removed (at least that's what I think that happened)

**Comment by L4cache** [comment]
你可以 fork 一个 ffmpeg 手动改，或者自己做一个 patch，也可以从 commit 历史中死者苏生
https://github.com/m-ab-s/mabs-patches/blob/a5c19970c4aa9024349947dea34168c15bd3f725/ffmpeg/0001-glslang-Remove-HLSL-and-OGLCompiler-libraries.patch

**Comment by LigH-de** [comment]
It would be lovely if you could return to English, I do not understand Japanese.

**Comment by L4cache** [comment]
That looks a lot like some problem specific to your environment, maybe you can try completely start from scratch, remove the non-ascii characters from your environment variables, or run m-ab-s in a virtual machine?
