### ISSUE TITLE
Request: EVC

### ISSUE THREAD

**Issue by esator** [jb-alvarado/media-autobuild_suite#2660]
Since 7.0 has evc support:
```
version 7.0:
- EVC decoding using external library libxevd
- EVC encoding using external library libxeve
```
and also gyan.dev builds
```
2024-04-04
added libxevd and libxeve for MPEG-5 EVC decoding and encoding respectively to full builds
```
https://github.com/mpeg5/xeve
https://github.com/mpeg5/xevd

https://github.com/mpeg5/ffevc

**Comment by l-l-l-l-l-l** [comment]
While they don't add the function, I'd suggest building XeVe and XeVd separatedly and adding ```--enable-libxeve
--enable-libxevd``` to ffmpeg_options.txt

You need to move ```xevd.h
xeve.h
xevd_exports.h
xeve_exports.h``` to `local64/include` ```libxevd.a
libxeve.a``` to `local64/lib` ```xevd.pc
xeve.pc``` to `local64/lib/pkgconfig` and ```libxevd.dll
libxeve.dll
xevd_app.exe
xeve_app.exe``` to `local64/bin-video`

You need to compile both prjects as dev and XeVe as main (otherwise you'll only have access to baseline).
I'm not sure if you need to move the exe files, but I'm not going to try removing them from there.
