### ISSUE TITLE
--disable-avisynth; how?

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#278]
I am not a user of AviSynth, so ffmpeg support 
for it is of little (or no) interest to me...
 Searching for a way to disable it in my custom 
compile, I chose `ffmpegChoice=1` but then saw 
that `--enable-avisynth` did not appear as an entry 
I could comment out in ffmpeg_options.txt

Being a relative newbie, I thought that adding 
`--disable-avisynth` in ffmpeg_options.txt 
would probably do it! Alas, after the compilation 
finished, the ffmpeg binary had both 
`--enable-avisynth --disable-avisynth` 
inside its configuration!

After some investigation, I located line 4 of "media-suite_compile.sh" 
`FFMPEG_BASE_OPTS=("--enable-avisynth" "--pkg-config-flags=--static")`
which implies AviSynth support is enabled in a mandatory fashion.
You, of course, know better, but can you please elaborate a bit?

[I am only responsible for my own doings, so I ended up 
removing "--enable-avisynth" from line 4, then moved on to 
line 50 of "media-autobuild_suite.bat", where I added `--enable-avisynth` 
in `set ffmpeg_options=`. That way, the option --enable-avisynth 
appeared inside ffmpeg_options.txt - I commented it out 
and the final ffmpeg binary has no mention of "avisynth" 
in its configuration (not sure, though, if my patches did 
actually disable avisynth support...). 
Please advise for a better solution...]

Kind regards

**Comment by wiiaboo** [comment]
It doesn't add anything to FFmpeg. Avisynth is loaded dynamically. Having it disabled or enabled shouldn't matter to filesize or resources used if you don't use it. It's a couple KBs at most that you save by not including it.
If you add `--disable-avisynth` it probably does disable it since FFmpeg respects the last option passed. You can check by running `ffmpeg -formats` and checking if `avisynth` is listed.

I don't have a strong opinion on Avisynth since I don't use and it's mostly dead, so I'll just move it to the default options.

**Comment by Vangelis66** [comment]
> If you add --disable-avisynth it probably does disable it 
> since FFmpeg respects the last option passed. 
> You can check by running ffmpeg -formats 
> and checking if avisynth is listed.

Unfortunately, that binary with both 
`--enable-avisynth --disable-avisynth` 
has been wiped out from hard disk...

> so I'll just move it to the default options.

Many thanks for that...
Regards.
