### ISSUE TITLE
librtmp & openssl query

### ISSUE THREAD

**Issue by Vangelis66** [jb-alvarado/media-autobuild_suite#287]
In the wiki it's mentioned that: 
> --enable-librtmp (rtmp protocol)
> FFmpeg has native support for the same protocols as librtmp 
> (rtmp(t)e needs --enable-gmp or --enable-gcrypt)

so --enable-librtmp is not strictly needed.
But does `(rtmp(t)e needs --enable-gmp or --enable-gcrypt)` 
apply to either librtmp / native ffmpeg RTMP support?

... because from running: 
`$ cd /build/ffmpeg-git && ./configure --help` 

 > --enable-gcrypt          enable gcrypt, needed for rtmp(t)e support
 >                           if openssl, librtmp or gmp is not used [no]
  > --enable-gmp             enable gmp, needed for rtmp(t)e support
 >                           if openssl or librtmp is not used [no]
 >  --enable-gnutls          enable gnutls, needed for https support
 >                          if openssl is not used [no]

it appears (to me, at least) that if "librtmp is used", 
it excludes the need for either gcrypt/gmp. 
Perhaps the answer could be made more 
clear in the wiki for newbies such as I...

What if: 
1. I want to compile the rtmpfoo binaries (foo=dump/srv/suck/gw)
2. Not enable librtmp in the compiled ffmpeg?
What would be the settings to achieve that?
Is `rtmpdump=1` inside "media-autobuild_suite.ini" 
totally unrelated to the presence/absence of `--enable-librtmp` 
inside "ffmpeg_options.txt" ? IOW, can I compile rtmpdump 
even without  `--enable-librtmp` ?

Finally, regarding the standalone rtmpdump: 

From within "media-autobuild_suite.bat" I read: 
> echo. In the case of rtmpdump, since its binaries are GPL, it will be compiled
> echo. with GnuTLS if LGPL is chosen, but if Non-free will use OpenSSL.

From using the suite more than 1.5 years ago, even when
`--enable-nonfree` was used to include libfdk_aac support, 
--enable-gnutls (at version 3.3.3 back then) was used as the 
SSL lib; the compilation of rtmpdump would use that, which 
resulted in huge executables (stripped rtmpdump.exe @ 3.34 MB, 
still have those on disk).
On the rtmpdump site, they indicate it can also be compiled with 
PolarSSL, now rebranded to "[mbedTLS](https://tls.mbed.org/)". 
This is under GPLv2.0 and produces quite small redistributable binaries 
([KSV](https://github.com/K-S-V/Scripts/releases)'s very popular rtmpdump fork uses PolarSSL). 
Do you think it would be relatively easy to add the 
ability to compile rtmpdump with PolarSSL (mbedTLS) ?

FWIW, I used `rtmpdump=1` & `--enable-librtmp --enable-nonfree` 
in my compiles, so OpenSSL was used, thus resulting in medium sized, 
1.78 MB, but undistributable binaries. BTW, is that a recent change, 
because the [Zeranoe](https://ffmpeg.zeranoe.com/forum/viewtopic.php?p=4489#p4489) builds from 2014 
use OpenSSL and are still there for download...

Since we do not compile OpenSSL locally but rather use 
the version shifted with mingw32, this presents a flaw security-wise. 
When I compiled my rtmpdump binary on Feb 20th,
`$ openssl version` produced  `OpenSSL 1.0.2e 03 Dec 2015`
so it's safe to assume rtmpdump was linked to that version.
On the [OpenSSL](http://www.openssl.org/news/newslog.html) site though, newer version 1.0.2f 
was on offer from Jan 28th!
My msys2 installation was updated by the main script 
on Feb 25th, the update did install OpenSSL 1.0.2f: 
`$ openssl version => OpenSSL 1.0.2f  28 Jan 2016`
and I force-recompiled rtmpdump to be on the safe side!
BTW, new update (of OpenSSL) announced on Mar 1st. 
Maybe I am just being paranoid, but could 
you consider using always the latest OpenSSL 
version in the script?

I apologise for tormenting you like that, 
you surely deserve more "friendly" users, 
it's just that I am in a learning curve right 
now and hope to get most things straight 
in my head - only little way to go now, 
I assure you!
Highly appreciative of your constant efforts 
and guidance...

**Comment by wiiaboo** [comment]
>  it appears (to me, at least) that if "librtmp is used",
it excludes the need for either gcrypt/gmp.
Perhaps the answer could be made more
clear in the wiki for newbies such as I...

Done.

> Is rtmpdump=1 inside "media-autobuild_suite.ini"
totally unrelated to the presence/absence of --enable-librtmp
inside "ffmpeg_options.txt" ? IOW, can I compile rtmpdump
even without --enable-librtmp ?

Yes, that's exactly why it's still a choice. You can include librtmp without the binaries and you can compile the binaries without including it in FFmpeg.
I left that way because there's other things that use only rtmpdump instead of rtmp protocol in FFmpeg, so they need rtmpdump especifically (like Youtube-DL and livestreamer).
FDK-AAC also works the same way.
x264, x265 and vpx need to be turned on in the .ini to be compiled. This is so you can just update them once and keep including them in FFmpeg without having to update them every time. vpx gets updated a lot.

> Do you think it would be relatively easy to add the
ability to compile rtmpdump with PolarSSL (mbedTLS) ?

Maybe if FFmpeg adds it. If it's only for rtmpdump is kinda pointless. I'm not even compiling LibreSSL even though it'd be smaller and clearner than OpenSSL because it's also kinda pointless since MinGW's OpenSSL works more or less fine.

> BTW, is that a recent change,
because the Zeranoe builds from 2014
use OpenSSL and are still there for download...

GPL is incompatible with OpenSSL's license. That's true since GPLv2. You need to either change to LGPL or compile OpenSSL as a shared lib for it to be redistributable. I don't remember seeing any exception in rtmpdump's license regarding OpenSSL so I assume it's still incompatible.

> Maybe I am just being paranoid, but could
you consider using always the latest OpenSSL
version in the script?

It's only a problem for rtmpdump and I assume Msys themselves will rush the update if it's that important. Also, I personally don't regard rtmpdump as needing to be that paranoid about security.
You can delete rtmpdump.exe and force a rebuild yourself if you need. OpenSSL isn't updated that often.
If you're adamant that rtmpdump should be paranoid, I can add LibreSSL and use it instead of OpenSSL. It's a drop-in replacement for the latter.

**Comment by wiiaboo** [comment]
> You can delete rtmpdump.exe and force a rebuild yourself if you need.

09d626a759b149578db73f60c0a6c147f555fc53 should force rebuilds of librtmp if GnuTLS/LibreSSL were compiled recently.

ea4f7345faf2b77819440cd4d6658e543c31bd93 releases of LibreSSL used instead of OpenSSL. There's a new release every other month or so.

**Comment by Vangelis66** [comment]
>> Perhaps the answer could be made more
>> clear in the wiki for newbies such as I...

> Done.

Thank you! Much better now!

> x264, x265 and vpx need to be turned on in the .ini to be compiled.

...Hmm, I think I'm losing you there (?) 
(my advancing age is starting to making it 
more difficult to digest simple but new things... :-( ) 
Taking vpx as example, what is true: 
1. --enable-vpx (options) on its own does nothing?
2. --enable-vpx (options) actually also needs vpx2=1 (ini) ?
3. vpx2=1 (ini) on its own will just compile static lib (libvpx.a) 
that WON'T be included/enabled in FFmpeg?

> This is so you can just update them once 
> and keep including them in FFmpeg 
> without having to update them every time. 
> vpx gets updated a lot.

... and that should be 
1. vpx2=1 (ini) , ffmpegB=2 (ini) , #--enable-vpx (options) 
to just compile libvpx.a in a first run, then 
2. vpx2=2 (ini) , ffmpegB=1 (ini) , --enable-vpx (options) 
to incorporate already compiled once lib into ffmpeg binary?

>  I'm not even compiling LibreSSL even though 
> it'd be smaller and cleaner than OpenSSL

TBH, I wasn't aware of LibreSSL; I found out it's 
a more secure fork of OpenSSL, that gets more 
frequent updates. Is its licence status the same 
as OpenSSL's ?

> https://github.com/jb-alvarado/media-autobuild_suite/commit/09d626a759b149578db73f60c0a6c147f555fc53 should force rebuilds of librtmp if GnuTLS/LibreSSL were compiled recently.

Will that also include rtmpdump.exe if `rtmpdump=1 (ini)`, 
or manual deletion first would be required?

> I can add LibreSSL and use it instead of OpenSSL
> https://github.com/jb-alvarado/media-autobuild_suite/commit/ea4f7345faf2b77819440cd4d6658e543c31bd93 releases of LibreSSL used instead of OpenSSL. 

Even though I feel guilty for causing  you extra work, 
many thanks for making rtmpdump and ffmpeg binaries 
more secure (if using --enable-openssl, which, as I 
understand it now, is an alias for --enable-libressl ).

One final wish/request  for rtmpdump: 
When the compiled binary is run, it is 
just reporting as being `RTMPDump v2.4`
Tag 2.4 is just too old now (2011-07-12), I have many "2.4" 
binaries on disk already and can't easily tell which is newer or older. 
I do not know if at all feasible, but could we patch it 
to report more info, like the git commit hash it was built upon, 
hopefully also info about the crypto lib used?
I would envision something like: 
`RTMPDump v2.4-20151223-gfa8646d-OpenSSL_1.0.2f-x86-static`

It should be possible to some extent, KSV's fork 
does print slightly more info than  "2.4" : 
`RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)`

May you be always blessed for keeping this superb 
(but so expensive in maintenance costs) project alive!

Regards.

**Comment by wiiaboo** [comment]
> 1. --enable-vpx (options) on its own does nothing?

It does if vpx was previously compiled. It doesn't update vpx, just includes it if a compiled version is installed.

> 2. --enable-vpx (options) actually also needs vpx2=1 (ini) ?

--enable-libvpx adds it to FFmpeg, the `vpx2` choice updates it or not. If libvpx isn't installed, the script removes `--enable-libvpx` so FFmpeg's configure doesn't fail.

> 3. vpx2=1 (ini) on its own will just compile static lib (libvpx.a)
that WON'T be included/enabled in FFmpeg?

If there isn't `--enable-libvpx` in ffmpeg_options.txt, correct. This is made so people can just compile vpxenc.exe and not including it in FFmpeg if they don't want to. Same with x264 and x265.

> 1. vpx2=1 (ini) , ffmpegB=2 (ini) , #--enable-vpx (options)
to just compile libvpx.a in a first run, then
2. vpx2=2 (ini) , ffmpegB=1 (ini) , --enable-vpx (options)
to incorporate already compiled once lib into ffmpeg binary?

You just need to change "vpx2". The following runs, if you don't care about updating libvpx you change it to vpx2=2. ffmpegB and the option can stay both times.

> Is its licence status the same
as OpenSSL's ?

Being a fork, yes. If it had a GPL-compatible license we'd just drop GnuTLS since it wouldn't be needed.

> Will that also include rtmpdump.exe if rtmpdump=1 (ini),
or manual deletion first would be required?

It includes the binary, yes. It doesn't check the binary for it, it checks /local(32|64)/lib/pkgconfig/librtmp.pc if either libssl (Open/LibreSSL) or gnutls were used in compilation.

> I would envision something like:
RTMPDump v2.4-20151223-gfa8646d-OpenSSL_1.0.2f-x86-static

Done.

**Comment by Vangelis66** [comment]
@wiiaboo wrote:
>> I would envision something like:
>> RTMPDump v2.4-**20151223**-gfa8646d-OpenSSL_1.0.2f-x86-static
>
> Done.

 Hello Ricardo, 
I haven't thanked you for implementing this, 
...but (sadly there is a "but") I think you 
misunderstood one part!

Currently the suite is still running, having updated it 
to snapshot https://github.com/jb-alvarado/media-autobuild_suite/commit/4da028e, 
but rtmpdump.exe has been already re-compiled. 
Yes, it's smaller now with LibreSSL (1.55 MB as opposed 
to 1.78 MB with OpenSSL), when run, the info reported is: 
`RTMPDump v2.4-20160302-gfa8646d-LibreSSL_2.3.2-i686-static`

which is great, but `**20160302**` is the compilation date (today).
**20151223** in my initial request is the date that commit 
git-fa8646d was pushed on the official rtmpdump git repo: 
http://repo.or.cz/rtmpdump.git/shortlog
If still possible, I would like that "push" date to be reported, 
to be more in sync with KSV's fork: 
`RTMPDump v2.4 GIT-2015-12-14 (Compiled by KSV)`
Again, GIT-2015-12-14 would be the git original source 
(probably git-530f9bb) upon which he had applied his patch.

Getting the compilation date out of the rtmpdump executable 
is a simple thing, by examining the "Date modified" info from 
file properties (it says 02/03/2016 19:43 EET), so not really 
needed to be also output by the binary itself!

Apologies for the misunderstanding caused!
With one thing or the other, today has been 
a full day for you already!
Cheers and congrats for your efforts!

**Comment by wiiaboo** [comment]
Done.
