### ISSUE TITLE
harfbuzz-1.2.1: No such file or directory

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#290]
script stops at the beginning with:
> Starting 32bit compilation of all tools
Imported FFmpeg options from ffmpeg_options.txt
License: gplv3
Imported mpv options from mpv_options.txt

> Starting 32bit compilation of global tools
freetype2 2.6.3 ........................................... [Up-to-date]
fontconfig 2.11.94 ........................................ [Up-to-date]
harfbuzz 1.2.1 .............................................. [Outdated]
├ Running extract...
/build/media-suite_helper.sh: line 47: cd: harfbuzz-1.2.1: No such file or directory
Failed changing to directory harfbuzz-1.2.1.

**Comment by ConvertApple** [comment]
I got as far as ffmpeg compiling but it couldn't find x265. 
So I changed options to not compile x265 in now I get this harfbuzz error.

Has the latest version of this script been run from scratch recently by the devs? 
The script is a fantastic concept, as compiling ffmpeg + libs for windows is otherwise impossible. It's a shame for all that excellent hard work to not produce an ffmpeg.exe at the end of it :(

**Comment by nille02** [comment]
If you change line 114 in media-suite_compile.sh
```        harfbuzz_ver=$(get_last_version "$harfbuzz_ver" "" "1\.\d+\.\d+") || harfbuzz_ver="1.2.1"```

to 
```        harfbuzz_ver=$(get_last_version "$harfbuzz_ver" "" "1\.\d+\.\d+") || harfbuzz_ver="1.2.3"```

It should fix the harfbuzz issue.

**Comment by wiiaboo** [comment]
> Has the latest version of this script been run from scratch recently by the devs? 

I run it every day with my small selection of options. I don't care about compiling every single thing the suite has. Have you noticed how much stuff this builds if you turn everything on? Would you prefer I remove/disable everything except that which I use personally?

> If you change line 114 in media-suite_compile.sh

That does fix it, probably but it shouldn't be needed. That's in case it fails to get the last version from the server.

**Comment by Vangelis66** [comment]
@ConvertApple wrote: 

> Has the latest version of this script been run from scratch recently by the devs?

I think you're being a tad harsh, here...
@wiiaboo is currently doing a sterling job 
in keeping this project alive, he has an excellent 
record of replying to bug reports, usually within hours, 
and he's also very generous in providing help & 
guidance to users and newbies like myself :-) 

The suite is pretty complex, various people want 
different things compiled and with different configurations 
(apart from the main ffmpeg binary), it is not humanly possible 
/ convenient to test every single permutation of options, 
especially as tests take some time (hours) 
even with recent powerful boxes...
I suspect wiiaboo has (like you & me) real life 
outside "media-autobuild_suite", so you should be 
"cutting him some slack"...

> as compiling ffmpeg + libs for windows is otherwise impossible.

While the suite is indeed the most convenient way 
for me, since I have now very limited C partition space 
and am currently running it from an external HDD, 
your statement is a hyperbole; you can istall a Linux distro, 
either natively or in a VM, and croos-compile ffmpeg 
and other libs, use Cygwin or standalone MinGW (or other 
similar compilers) on your flavour of windows - there is 
ample documentation on line already...

@wiiaboo wrote:

> Would you prefer I remove/disable everything 
> except that which I use personally?

... Please do not! I am quite happy with 
the many choices currently available!

Again, many thanks 
(off now to try a new compiling session 
after recent fixes!).

**Comment by ConvertApple** [comment]
I merely enquired if the latest version of this script been run from scratch recently by the devs? as it may have got out of sync with the repositories. This seems to have been misinterpreted as a slur. I went on to say "The script is a fantastic concept"  and describe it as "excellent hard work".

I have previously compiled under windows using msys2 & cross compiled under OSX, via zeranoe forum which took a few days, however getting all the external libraries added in, as this does is not easy in non-linux environments.

Thanks again to the dev's of this fantastic script.
