### ISSUE TITLE
x265 failed,..

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#302]
> fatal: Not a git repository (or any of the parent directories): .git
All relevant logs have been anonimously uploaded to https://0x0.st/K_E.zip
Copy and paste [logs.zip](https://0x0.st/K_E.zip) in the GitHub issue.

**Comment by Vangelis66** [comment]
> All relevant logs have been **anonimously** uploaded

Hi - probably just a typo and I am again 
nitpicking, but since I am Greek and the 
origin of the word is also Greek (ανωνύμως), 
the correct spelling is **anonymously**.

BTW, any advantage of the non-github 
uploading of logs.zip (as compared to the 
previous behaviour of attaching it in the issue) ?

Thanks

**Comment by wiiaboo** [comment]
Advantage is being automatically uploaded and only you know the link until you paste it somewhere. If you think something sensitive is being upload (your machine username, basically), you can change yourself and upload somewhere else and forget the previous link. The file will eventually disappear.

**Comment by Vangelis66** [comment]
Thanks for the correction and detailed explanation.

 I thought to myself maybe GitHub (free) imposed a
bandwidth quota for uploads per project, but as 
you state that was not it...

Best regards
