### ISSUE TITLE
Feature request: allow to select a specific revision/commit

### ISSUE THREAD

**Issue by Selur** [jb-alvarado/media-autobuild_suite#304]
Would be nice if there would be a possibility to pin a build to a specific revision (svn) / commit (git), this way one could build older versions to easier trace errors.

**Comment by wiiaboo** [comment]
Just modify the scripts yourself and add "#commit=123456" to the end of the url. Simple enough.

**Comment by Vangelis66** [comment]
... I believe this is somewhat related: 

What I would have liked is the ability to 
compile released versions of FFmpeg 
(and not only HEAD), preferably of the 
latest branch (now in v3.0) and its subsequent 
point releases. 
Of course I understand the script is always 
evolving to handle upstream ffmpeg 
changes, so asking to compile older branches 
(like 2.8.x, 2.7.x etc.) is a bit unrealistic, 
but releases 3.x.x should be doable...

Back in November 2014, jb was kind enough 
to post "instructions-for-dummies" (yes, that's me...):

https://github.com/jb-alvarado/media-autobuild_suite/issues/28#issuecomment-62779065

but that was for ffmpeg-2.4.3, which was so long ago... 
Not only has the ffmpeg code itself changed, but in a 
more pronounced way the whole suite, too!

I do use ffmpeg quite frequently, but I do not always 
ask for the latest code; I would be OK if I just compiled 
the released versions every two months or so 
(yes, I know the ffmpeg people advise otherwise on 
their site... ).

I am less proficient than @Selur in manipulating 
the suite code, so I would kindly ask for tips on how 
to compile e.g. a non-free binary of release 3.0 
(or imminent release 3.1) - in the wiki there's a guide 
how to compile "_your own flac (32 bit) from source_"; 
perhaps in the future (this is low priority, so only **if** 
and **when** you can) one similar guide could be written 
for ffmpeg when its source is not git HEAD - this could prove 
indeed handy when one wants to test patches not yet 
merged in the official repo...

All the best

**Comment by wiiaboo** [comment]
>What I would have liked is the ability to
compile released versions of FFmpeg
(and not only HEAD), preferably of the
latest branch (now in v3.0) and its subsequent
point releases.
Of course I understand the script is always
evolving to handle upstream ffmpeg
changes, so asking to compile older branches
(like 2.8.x, 2.7.x etc.) is a bit unrealistic,
but releases 3.x.x should be doable...

Way too much work to add that feature to the suite itself, imo. Pull requests are welcome.
Unless it's just FFmpeg. I could add an extra option to compile the latest release. Not for anything else.

Compiling FFmpeg releases is just a matter of adding `#tag=n3.0` at the end of FFmpeg's git url.
Ex:
```bash
# git master
do_vcs "https://git.videolan.org/git/ffmpeg.git"

# 3.0 release
# source as was used for release 3.0
do_vcs "https://git.videolan.org/git/ffmpeg.git#tag=n3.0"

# 3.0 branch
# fixes get backported here, so they're included in next 3.0.x releases
do_vcs "https://git.videolan.org/git/ffmpeg.git#branch=release/3.0"

# 2.8.6 release
do_vcs "https://git.videolan.org/git/ffmpeg.git#tag=n2.8.6"
```
Quite simple.

Take care to change the main build of FFmpeg and not the light one that's only meant for x264.
Search for `ffmpeg.git` and change the second one.

**Comment by wiiaboo** [comment]
To test patches not on git head, you should never use releases, so I don't get your last paragraph. 99% of the time, patches are meant to be applied on git head not on random releases.
And it's easier to just add a `do_patch <patch name> [am]` in the right place.
Or `source media-suite_helper.sh` and copy paste as needed.
Or just see what the convenience functions do and run the commands manually.

**Comment by wiiaboo** [comment]
You're welcome to add it to the FAQ, it's editable by all.

**Comment by mirh** [comment]
Done!
Now I'd love there was a list with little steps to do for any given version. 😛
E.g. in 2.8 to complete configure you have to:
* remove enable-gcrypt, enable-cuda,enable-cuvid, enable-schannel, enable-sdl2 and enable-libzimg flags
* change disable-sdl2 to disable-sdl in media-suite_helper.sh
* patch openjpeg detection so that it can find libraries from newer versions

**Comment by wiiaboo** [comment]
That's why it's not supported. I don't have time to keep track of changes like those. Nor would I care to, even if I had time, since most of the time you should be using the latest release which is close enough to git.

**Comment by mirh** [comment]
Absolutely. 
Too bad I need to bisect ffmpeg in order to solve an issue that keeps me away from git :s

**Comment by wiiaboo** [comment]
You don't need to run the whole just to bisect ffmpeg. Build everything you need and then do the steps manually for ffmpeg. It's easy enough.
