### ISSUE TITLE
recipe for target 'libavfilter/avfilter-6.dll' failed

### ISSUE THREAD

**Issue by HengtianPan** [jb-alvarado/media-autobuild_suite#318]
https://0x0.st/PWG.zip

**Comment by wiiaboo** [comment]
Please don't copy paste the entire log.

**Comment by wiiaboo** [comment]
Also, you're using different files. Is the issue reproducible with the suite itself?

**Comment by wiiaboo** [comment]
From the logs I can't see anything wrong. Try removing libs from ffmpeg_options.txt gradually until it works. Some lib is probably exporting symbols and overwriting FFmpeg's.

In the suite itself there should be no lib causing that, so unless it's a new issue, it's probably caused by your modifications.

**Comment by HengtianPan** [comment]
https://0x0.st/Pte.zip
I removed the "ffmpeg_options.txt", and run original script, is still wrong

**Comment by wiiaboo** [comment]
You haven't updated the script. It's been fixed already.

**Comment by HengtianPan** [comment]
Thanks  ;-)
