### ISSUE TITLE
proposal: add openh264

### ISSUE THREAD

**Issue by moppman** [jb-alvarado/media-autobuild_suite#335]
https://github.com/cisco/openh264
and https://ffmpeg.org/general.html#OpenH264

**Comment by wiiaboo** [comment]
Any reason why use it instead of x264? I remember it being much worse.

**Comment by moppman** [comment]
True, but it should be possible nonetheless, since there are valid use cases, e.g. http://stackoverflow.com/questions/34104764/trying-to-use-openh264-as-an-alternative-to-libx264-in-ffmpeg-c-project

**Comment by wiiaboo** [comment]
Pros relative to x264 are that it's BSD, therefore compatible with LGPL FFmpeg, but their patent offers are only applicable when using their binaries.

So, you can use it if you really need LGPL and you paid H.264 license. That looks like a very specific audience.

I added it because it was relatively easy to compile and doesn't take long, but it did need a patch for FFmpeg.

**Comment by moppman** [comment]
Cool, you're quick ;)
