### ISSUE TITLE
Why not gcc -O3 everywhere?

### ISSUE THREAD

**Issue by mario698** [jb-alvarado/media-autobuild_suite#358]
Hi,

I have noticed that some libs, for example libx264, are compiled with "O2" optimization option. I couldn't find a reason why you only use O2, since [O3 is generally considered safe nowadays](http://stackoverflow.com/questions/11546075/is-optimisation-level-o3-dangerous-in-g).

I did a quick test and replaced every occurrence of "O2" with "O3" in your compile script; this gave me a decent performance boost of about 5% when encoding a movie using the libx264 codec. Not much, but I wounder why you made that decision, compiling with O2 instead of O3. Did you encounter any serious issues?

**Comment by wiiaboo** [comment]
Not my decision, it's from official [MinGW makepkg](https://github.com/Alexpux/MSYS2-packages/blob/master/pacman/makepkg_mingw64.conf#L42-L62).
I myself have -O3 on CFLAGS using [this](https://github.com/jb-alvarado/media-autobuild_suite/blob/master/build/media-suite_compile.sh#L62) so I wouldn't mind changing. It should be usually left to the devs whether they are OK with higher O values.
x264 specifically is already using -O3 because the script removes `-O2` flags from CFLAGS before configure, so I don't know where this 5% boost of yours comes from.

**Comment by wiiaboo** [comment]
Also, from [Gentoo wiki](https://wiki.gentoo.org/wiki/GCC_optimization#-O) they themselves don't recommend using -O3, so I'd prefer not changing this. Use `"$HOME/custom_build_options"` file to replace global CFLAGS if you want for yourself instead of altering the scripts.
Mine as example: 
```bash
export CFLAGS="-mthreads -march=native -O3 -pipe"
export CXXFLAGS="${CFLAGS}"
```
