### ISSUE TITLE
Can't build curl

### ISSUE THREAD

**Issue by anana93** [jb-alvarado/media-autobuild_suite#423]
Using latest commit, the error still exist. Try not delete -> not works. Try delete like before still not works...

log:
https://0x0.st/_Rl.zip

**Comment by wiiaboo** [comment]
Can't reproduce. Can you force recompilation of libressl by deleting /local32/lib/libssl.a and try once again?

**Comment by anana93** [comment]
1st try
delete /local32/lib/libssl.a -> failed build curl

2nd try
not delete /local32/lib/libssl.a -> failed build curl

log:
https://0x0.st/_RC.zip

**Comment by wiiaboo** [comment]
Hard to reproduce without doing a fresh build, but I think I finally figured out what was the issue.

**Comment by wiiaboo** [comment]
Still can't reproduce, even with a fresh build. There's probably something in your environment messing with curl building unrelated to the suite. Try a fresh build on another directory closer to the disk root (don't move this one, do a completely fresh one with the latest commit of the suite) or try using gnutls instead of libressl, or even winssl. Change ffmpegChoice=4 to ffmpegChoice=1 and remove the line with --enable-openssl and uncomment any other optional libs you want in build/ffmpeg_options.txt.

If it still doesn't work, try asking in curl's bug tracker or appropriate channels for help.
