### ISSUE TITLE
Add skip externals update setting

### ISSUE THREAD

**Issue by mirh** [jb-alvarado/media-autobuild_suite#436]
More specifically I thought this would fit pretty well the already existing ffmpegUpdate, somehow like:
1. checks externals, checks ffmpeg, rebuild it if any changes
2. checks externals, checks ffmpeg, rebuild it only if it changes
3. don't check externals, checks ffmpeg, rebuild it only if it changes

Then, I was also fantasizing about a fourth "don't check externals, don't check ffmpeg, rebuild it every time", but.. I guess this use-case clashes with the one of manual steps you mentioned in https://github.com/jb-alvarado/media-autobuild_suite/issues/304#issuecomment-269381220
Were you referring to [this](https://github.com/jb-alvarado/media-autobuild_suite/wiki#here-is-a-example-how-to-build-your-own-flac-32-bit-from-source)?

**Comment by wiiaboo** [comment]
Your 1 is the same as ffmpegUpdate=1 == forces rebuild of FFmpeg if vpx/x264/x265 were updated.
Your 2 is the same as ffmpegUpdate=2 == doesn't force rebuild.
Your 3 is troublesome to implement. Every dependency would checks of its own.

Either way FFmpeg always gets rebuilt if there's an update to it since it's a git source.

**Comment by mirh** [comment]
Yes, I know 1 and 2 are what's already there (I just mentioned them to highlight the difference). 

When you say troublesome to implement, you are referring to the "don't check update, but only if already present and built" part of the thing?
