### ISSUE TITLE
Can you go back to using cyan for the "Updated" text color in mintty?

### ISSUE THREAD

**Issue by joetex72** [jb-alvarado/media-autobuild_suite#503]
The blue that's being used now hurts my eye. :[

**Comment by wiiaboo** [comment]
I haven't changed anything since I added the colors.

You must've changed the colors in mintty yourself and not realized it.
There should be a file in `/msys64/home/<username>/` called `mintty.rc`. That's where the colors' definitions are.

You can use whatever colors you want, there are [themes you can use](https://github.com/oumu/mintty-color-schemes).
