### ISSUE TITLE
error: mingw-w64-x86_64-clang: missing required signature

### ISSUE THREAD

**Issue by hydra3333** [jb-alvarado/media-autobuild_suite#518]
Hello, a first-time user here.  
Win8.1 in a VM, non-admin user.  
First-time build, choosing both x32 and x42, and the clang error keeps coming up.  
Suggestions welcomed.

firstrun.log
```
mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue': Permission denied
Copying skeleton files.
These files are for the users to personalise their msys2 experience.
They will never be overwritten nor automatically updated.
```

mingw32.log doesn't show any errors.

mingw64.log
```
(61/61) checking package integrity                                       [#######################################] 100%
error: mingw-w64-x86_64-clang: missing required signature
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```

**Comment by myfreeer** [comment]
https://github.com/Alexpux/MINGW-packages/issues/2477
upstream issue

**Comment by hydra3333** [comment]
OK, thanks. Wait and watch I guess.

**Comment by LigH-de** [comment]
Missed this one the first time because the suite update did not halt here (saw it when I tried right again); but a dependent issue might be that x264 does not build x86 10-bit because it can't find any assembler? (min. req. is nasm-2.13)

[logs.zip](https://0x0.st/EN_.zip) / [logs.zip](https://0x0.st/ENJ.zip)

Will try again when package has been fixed by MinGW project.

**Comment by wiiaboo** [comment]
That's completely unrelated to this issue, @LigH-de.

But I opened https://github.com/Alexpux/MINGW-packages/pull/2511

**Comment by wiiaboo** [comment]
Seems fixed on my side.
