### ISSUE TITLE
kvazaar.exe was built despite standalone=2 (take 2)

### ISSUE THREAD

**Issue by AnryCryman** [jb-alvarado/media-autobuild_suite#582]
Man, stop closing issues before they are resolved.

> Then don't use other265=1.

Why do you keep bringing it up? I told you numerous times that the problem has to do with standalone=2. What is so hard to comprehend?

```
echo. Build standalone binaries for libraries included in FFmpeg?
echo. eg. Compile opusenc.exe if --enable-libopus
echo. 1 = Yes
echo. 2 = No
```

What does it say in the description? Can you read? Are you literate?
Compile opusenc.exe if --enable-libopus if I select Yes. I chose No. Then it should NOT compile kvazaar.exe if --enable-kvazzar.
I found a bug in your script. You should be thankful. And you must fix it.

**Comment by wiiaboo** [comment]
Read the fucking option you selected.
It's not a bug, it wasn't explained correctly: https://github.com/jb-alvarado/media-autobuild_suite/commit/cb0a36fa2b9564e437b9e24927a15d9ed8a0ae6f
I'll block you if you keep annoying with this.

**Comment by wiiaboo** [comment]
The individual option is there because you might want to build kvazaar and not include it in FFmpeg.
Since there would be no point in building libkvazaar without it being used anywhere, the other265 option is for building the standalone.
If you enable it in ffmpeg_options.txt it'll get built and included to FFmpeg, whether other265 is 1 or 2.
This was always the goal. The standalone option is only meant for libs that get included into FFmpeg that don't have an individual option.

I hope this makes it fucking clear as water. If you disagree with it, send a pull request or shut the fuck up about it.
