### ISSUE TITLE
Compilation hangs after detecting libgcrpt is up-to-date

### ISSUE THREAD

**Issue by LigH-de** [jb-alvarado/media-autobuild_suite#630]
I wonder if any script is asking for a confirmation, but I see no console output because MSYS2 + mintty don't display any request until I confirmed (I remember such an issue exists, maybe with Python?).

```
        Starting 32bit compilation of all tools
Imported FFmpeg options from ffmpeg_options.txt
License: nonfree
Imported mpv options from mpv_options.txt

        Starting 32bit compilation of global tools
freetype2 2.8.1 ........................................... [Up-to-date]
fontconfig git ......................................... [Already built]
harfbuzz git ........................................... [Already built]
fribidi 0.19.7 ............................................ [Up-to-date]
libass git ............................................. [Already built]
libgcrypt 1.7.8 ........................................... [Up-to-date]
_
```
...

No. Pressing ENTER seems not to advance the progress. Entering 'y' neither.

**Comment by schmidthubert** [comment]
It seems to be stuck in next block gnutls not libgcrypt. Without that block the script will use gnutls libs from a previous built. Not a nice solution at all but better than nothing for now ... :relieved:

**Comment by LigH-de** [comment]
Well, just before this issue occured, I edited ffmpeg_options.txt to enable most options, but ensured to keep `--enable-openssl` commented out while having `--enable-gnutls` enabled.

Is there possibly a logic issue in the previous patch [d2fbc6d](https://github.com/jb-alvarado/media-autobuild_suite/commit/d2fbc6d83704da55fa79c0f283d8ff2e12ced856) for this case?

**Comment by schmidthubert** [comment]
By looking at the gnutls block I don't see a relation to that helper patch. Just wait for Ricardo to explain and fix it. :thumbsup:

**Comment by Metaphorce812** [comment]
Yeah the problem is definitely related to libssl/libressl. I got the exact same error as you, so I commented out `--enable-gnutls` and un-commented `--enable-openssl`. Then libssl/libressl successfully updated, but when MABS tried to build ffmpeg I got the error from #623 again. So then I tried re-enabling gnutls and disabling openssl in ffmpeg_options.txt, hoping that the bug wouldn't be an issue since libssl/libressl was up-to date, but I just got the same hang from this issue again. So right now I can't build ffmpeg with gnutls OR openssl enabled.

**Comment by schmidthubert** [comment]
There's another construction site ahead with a recent change in x265, so more git problems because of "stable switch(es)" missing in MABS script(s).  At least libavcodec is at 58.2.100 now since hwaccel CUVID became NVDEC so everyone who doesn't know and cannot temp fix these problems by themselves have to wait for MABS maintainer(s) to fix the problems here ...

**Comment by pat357** [comment]
The issue is in the gnutls part of the script.
I could narrow it down to this line 
```
do_wget "ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/gnutls-${gnutls_ver}.tar.xz"
```
Notice I replaced the /v3.5/ with /v3.6/ in the script, since the latest version is v3.6.1 located in the "v3.6" directory on the server. And yes , gnutls_ver="3.6.1" before entering that command.

Even after following command, there is **no output and it just seems to hang**:
```  
do_wget "ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/gnutls-3.6.1.tar.xz"
```
It seems like "ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/gnutls-3.6.1.tar.xz" is working with my browser, but **not when using do_wget.**

After downloading with **browser** and extracting it in "**gnutls-3.6.1**" directory, the compilation is fine.
Somewhere in the "**do_wget**" function, things go wrong, but donno what or where yet.

**Comment by hydra3333** [comment]
maybe https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/gnutls-3.6.1.tar.xz which seems to work.

**Comment by LigH-de** [comment]
With the following edit in `media-suite_compile.sh` the suite passes with enabled gnutls and disabled openssl (up to the issue in #623 of course). Sorry for the verbose paste, I am not so used to creating diff patches yet... lines 234-256:

```
if { { [[ $ffmpeg != "no" ]] && enabled gnutls; } ||
    [[ $rtmpdump = y && $license != nonfree ]]; }; then
    [[ -z "$gnutls_ver" ]] &&
        gnutls_ver="$("${curl_opts[@]}" -l "ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/")" &&
        gnutls_ver="$(get_last_version "$gnutls_ver" "xz$" '3\.6\.\d+(\.\d+)?')"
    gnutls_ver="${gnutls_ver:-3.6.1}"
    _check=(libgnutls.{,l}a gnutls.pc)
    if do_pkgConfig "gnutls = $gnutls_ver"; then
        do_pacman_install nettle
        do_wget "https://www.gnupg.org/gcrypt/gnutls/v3.6/gnutls-${gnutls_ver}.tar.xz"
        do_uninstall include/gnutls "${_check[@]}"
        /usr/bin/grep -q "crypt32" lib/gnutls.pc.in ||
            sed -i 's/Libs.private.*/& -lcrypt32/' lib/gnutls.pc.in
        do_separate_confmakeinstall \
            --disable-{cxx,doc,tools,tests,rpath,libdane,guile} \
            --without-{p11-kit,idn,tpm} --enable-local-libopts \
            --with-included-unistring \
            LDFLAGS="$LDFLAGS -L${LOCALDESTDIR}/lib -L${MINGW_PREFIX}/lib"
        do_checkIfExist
    fi
    grep -q "lib.*\.a" "$(file_installed gnutls.pc)" &&
        sed -ri "s;($LOCALDESTDIR|$MINGW_PREFIX)/lib/lib(\w+).a;-l\2;g" "$(file_installed gnutls.pc)"
fi
```
I don't know whether this is at all relevant...

**Comment by Selur** [comment]
@LigH-de: Removed '--enable openssl' from the ffmpeg parameter inside the bat and replaced the lines you posted above. Script still hangs in the script part with your replacement.
using slightly different urls (like hydra3333 posted) seems to help. 
so
https://www.gnupg.org/ftp/gcrypt/gnutls/v3.6/
and
instead of ftp://ftp.gnutls.org/gcrypt/gnutls/v3.6/ and https://www.gnupg.org/gcrypt/gnutls/v3.6/

**Comment by LigH-de** [comment]
Oh, I missed the /ftp/...

**Comment by Metaphorce812** [comment]
@LigH-de @Selur Awesome work guys - I _finally_ got MABS to successfully build ffmpeg by copying that code into `build\media-suite_compile.sh` and removing `--enable-openssl` from `media-autobuild_suite.bat`

**Comment by LigH-de** [comment]
But just commenting out `#--enable-openssl` in **ffmpeg_options.txt** is not sufficient? Then I wonder where you deleted how much.

**Comment by Selur** [comment]
@LigH-de : adjusting the gnutls path is still necessary,.. so he removed the '--enable-openssl' and copied your code with the adjusted paths. -> same here :) (using zeranoes ffmpeg version here)

**Comment by LigH-de** [comment]
OK, I checked everything again and found a mistake in my current configuration. So, after applying the patch to the gnutls URL's, and commenting out openssl, this time the suite starts building gnutls. This time it seems to work as expected...

**Comment by BlackScreen** [comment]
@LigH-de: Thank you for your change in code. This helped me building the whole suite again.
I used that change and the TXT-file from @Metaphorce812 in #623. Thank you both!

**Comment by kliffgomel** [comment]
Issue can be closed.

**Comment by Metaphorce812** [comment]
For anyone still having problems, here are my modified `media-suite_compile.sh` (with fixed fribidi and gnutls links), `media-autobuild_suite.bat` (with `--enable-openssl` removed), `ffmpeg_options.txt` (with everything but openssl enabled), and `media-autobuild_suite.ini` files. `media-autobuild_suite.bat` goes in the base MABS directory and the other three go in the build folder.
`media-autobuild_suite.ini` is set to my personal preferences (64-bit only, static ffmpeg, separate binaries for everything except mpv and ffmbc) and you don't necessarily need it. However, **to build a full working version of ffmpeg using that `ffmpeg_options.txt` file, `media-autobuild_suite.ini` needs `ffmpegChoice=1` and `license2=1`.**
So you can modify your own `media-autobuild_suite.ini`, or delete yours and set the options to what you want when you run `media-autobuild_suite.bat` (making sure to choose "Non-free" for the license and "Yes" for "Choose ffmpeg and mpv optional libraries?"), or download mine (and modify it to however you want). Since the options in `media-autobuild_suite.ini` aren't self-explanatory, you can set the ones you're not sure about to 0, and then when you run `media-autobuild_suite.bat` it will give you the prompt to choose those options.

### **[MABS_2017.11.20.zip](https://github.com/jb-alvarado/media-autobuild_suite/files/1489398/MABS_2017.11.20.zip)**

Disclaimer: These files work right now, but could stop working at any point because of developers changing/messing stuff up (i.e., how we got into this confusing mess in the first place).

P.S. You can edit `media-autobuild_suite.ini` by opening it with Windows' default Notepad program, but [Notepad++](https://notepad-plus-plus.org/download/) is superior in every way, very useful, and I highly recommend installing it (the 32-bit version because the 64-bit version doesn't work with most of the available plug-ins).
