### ISSUE TITLE
Building with NewTek NDI Enabled?

### ISSUE THREAD

**Issue by jules43** [jb-alvarado/media-autobuild_suite#721]
Do you have any plans to support building with NDI enabled?

https://www.newtek.com/blog/ffmpeg-3-4-adds-ndi-io/
https://git.videolan.org/?p=ffmpeg.git;a=blob_plain;f=Changelog;hb=n3.4

Thanks

Jules

**Comment by BlackScreen** [comment]
This sounds cool, would like to try that!

**Comment by wiiaboo** [comment]
You're welcome to try yourself. The suite doesn't delete options it doesn't recognize.

**Comment by wiiaboo** [comment]
Looks like it's exactly the same shit as decklink, yeah no. If someone volunteers to do this shit job of getting the SDK, you're welcome.

**Comment by BlackScreen** [comment]
I have downloaded the SDK. Are this the files you need?
https://ufile.io/bouqu

**Comment by wiiaboo** [comment]
Not enough to build. The configure check requires only the headers, sure, but linking requires some "ndi" lib too.

**Comment by BlackScreen** [comment]
Ok, probably deleted something important then. I have re-uploaded a part of the SDK (excluding the tools):
https://ufile.io/2cdsg

**Comment by wiiaboo** [comment]
Looking at those headers, I don't think they thought of supporting libndi with mingw GCC, only MSVC, so yeah, this is a wontfix.

**Comment by BlackScreen** [comment]
Ok, thanks for looking into it.

**Comment by jules43** [comment]
That's for investigating. I have requested NDI to provide mingw GCC lib as part of their SDK.

**Comment by jules43** [comment]
I asked about this on the NewTek forum and they said:

Actually, I do not think that to use the FFMPEG version of NDI you need any kind of support for MSVC. If I remember correctly they implemented it using dynamic binding (i.e. LoadLibrary) which means that they should be able to include it as part of the standard builds. Whats more, we released our SDK header files under the MIT license so that they can even be included in the FFMPEG source code if they want to facilitate building. If someone wants to work with us on this, just have them email ndi@newtek.com and we'll help make this happen.

**Comment by wiiaboo** [comment]
> Whats more, we released our SDK header files under the MIT license so that they can even be included in the FFMPEG source code if they want to facilitate building.

No. The devs are thinking of removing all third-party headers on their repo, they won't accept those.

**Comment by wiiaboo** [comment]
I'm not registering an account on newtek just for this, so whoever still cares about this, forward to them, since I see a lot of people thinking this is not newtek's problem.

Things needed for this to work:
- don't put the SDK behind a fucking registration wall, put it somewhere publicly and anonymously accessible; also, don't put it inside an installer, that's unusable for redistribution and building automation
- FFmpeg expects ndi.lib or libndi.[dll.]a, because that's the normal name of a library and is what's available in both macOS and Linux versions of the SDK.
- MinGW GCC doesn't set MSC_VER (nor should it set it, for very obvious reasons), so this is broken in Processing.NDI.Lib.h and probably other headers:
```C
#ifdef _WIN32
#define PROCESSINGNDILIB_DEPRECATED __declspec(deprecated)
#ifdef PROCESSINGNDILIB_EXPORTS
#ifdef __cplusplus
#define PROCESSINGNDILIB_API extern "C" __declspec(dllexport)
#else
#define PROCESSINGNDILIB_API __declspec(dllexport)
#endif
#else
#ifdef __cplusplus
#define PROCESSINGNDILIB_API extern "C" __declspec(dllimport)
#else
#define PROCESSINGNDILIB_API __declspec(dllimport)
#endif
#ifdef _MSC_VER
#ifdef _WIN64
#define NDILIB_LIBRARY_NAME			"Processing.NDI.Lib.x64.dll"
#define NDILIB_REDIST_FOLDER		"NDI_RUNTIME_DIR_V3"
#define NDILIB_REDIST_URL			"http://new.tk/NDIRedistV3"
#else
#define NDILIB_LIBRARY_NAME			"Processing.NDI.Lib.x86.dll"
#define NDILIB_REDIST_FOLDER		"NDI_RUNTIME_DIR_V3"
#define NDILIB_REDIST_URL			"http://new.tk/NDIRedistV3"
#endif
#endif
#endif
#else
```

**Comment by wiiaboo** [comment]
Most importantly, like Decklink's SDK, this clause makes the SDK nonfree, so FFmpeg compiled with it will never be legally redistributable:
```
d.	Unless otherwise stated in the SDK, no files within the SDK and the Specific SDK may be distributed. 
```

**Comment by BlackScreen** [comment]
Maybe this would be a solution? Someone on the forum at Zeranoe contacted NDI:
https://ffmpeg.zeranoe.com/forum/viewtopic.php?p=13243#p13243
I get that it would have to be implemented in FFmpeg first, but after that maybe here?

**Comment by wiiaboo** [comment]
Problem with their comparison with nvenc is that people get nvenc support by buying Nvidia's GPUs and installing their driver. Being a GPU, it's sort of considered a system library so that's why it's not nonfree, even though it depends on proprietary libraries.

The headers are probably still considered nonfree since they're part of a non-redistributable SDK, even though they are licensed under MIT. FFmpeg will not include them, so Newtek would have to make them available somewhere public.

**Comment by wiiaboo** [comment]
In fact, instead of learning from Nvidia's shitty example on how not to do FOSS-friendly SDKs, point them to AMD instead: https://github.com/GPUOpen-LibrariesAndSDKs/AMF/tree/master/amf/public/include

**Comment by wiiaboo** [comment]
And they went and did just the opposite, nice going. Good luck getting that merged.

**Comment by adamgf** [comment]
How do I get an ffmpeg build for Mac OS X High Sierra that statically links in all the required NDI libraries to stream NDI?
