### ISSUE TITLE
How to? last release build

### ISSUE THREAD

**Issue by alex6dj** [jb-alvarado/media-autobuild_suite#749]
There is some way to select the latest release version (Ex 3.4.2). Or this can only compile the last existing version, whether stable or not.

By the way, excellent work. So far it's the only project I've tried that works as it is.

**Comment by wiiaboo** [comment]
Sure, https://github.com/jb-alvarado/media-autobuild_suite/issues/644#issuecomment-347990602

But it's probably not going to ever be an official option, since I really don't want to keep old patches around and deal with backports. If it ever ends up being an option, it won't be officially supported.

**Comment by alex6dj** [comment]
OK, thank´s
