### ISSUE TITLE
Fails to find SRT using pkg-config

### ISSUE THREAD

**Issue by 1480c1** [jb-alvarado/media-autobuild_suite#936]
When building ffmpeg, the compilation of ffmpeg throws the error that it cannot find srt >=1.3.0 using pkg-config and cannot continue. Running pkg-config --modversion srt in the mintty shell returns 1.3.1. This has happened with two clean versions downloaded using git clone.

 [logs.zip](https://0x0.st/s3hb.zip)

**Comment by 1480c1** [comment]
If I turn off srt in the ffmpeg options, the next error that I encounter is openssl not being found.
[logs.zip](https://0x0.st/sYrD.zip)

**Comment by wiiaboo** [comment]
The first issue is fixed with 5d0f12c.

Concerning the second issue, try updating the suite if you haven't already, there's a new minor version of openssl.

**Comment by wiiaboo** [comment]
What multiplex? It should be disabled in mingw, so you shouldn't be getting any error with it.
> Tried the version that was released around 12 hours ago.

Well, I pushed the commit with the fix 22 minutes ago, so it being broken 12 hours ago isn't really relevant.

**Comment by wiiaboo** [comment]
~~What multiplex? It should be disabled in mingw, so you shouldn't be getting any error with it.~~
> Tried the version that was released around 12 hours ago.

~~Well, I pushed the commit with the fix 22 minutes ago, so it being broken 12 hours ago isn't really relevant.~~

Don't ask to upload logs, just upload them, next time.
Should be fixed with 4f5f9f8.
