### ISSUE TITLE
:delete label misplaced?

### ISSUE THREAD

**Issue by 1480c1** [jb-alvarado/media-autobuild_suite#988]
Hello, so while looking through the bat file for trying to create a ps1 for it ( can be found at [media-autobuild_suite](https://github.com/Randomderp/media-autobuild_suite/blob/master/media-autobuild_suite.ps1) for now) I noticed a couple of things, first being that the ":delete" label in line 931 is placed after `set "writeDel=no" if %deleteSourceINI%==0 (` while the other labels are placed before. Is this intentional? Also, when I tried to run the bat file untouched and pressed enter at the question without an input, the prompt threw a `set was unexpected at this time.`

Edit: I guess it's because there is no catch for if there was no input as even though there is a catch for if the answer is outside the bounds (1 or 2), there is none for if its null or unanswered.

**Comment by wiiaboo** [comment]
Seems [intended](https://github.com/jb-alvarado/media-autobuild_suite/commit/b99387b27176393ac57e247c8725c0716ea3c5ba), but I can't really remember the exact reason why.

Looks good so far on the conversion to powershell. While you're at it, if instead of the .ini you could use JSON, YAML or some other more readable and more robust configuration file, it'd be great.

**Comment by 1480c1** [comment]
Okay, probably will try to use json. Mainly coded it on the idea for it to be a drop in to the folder in case someone only does git pull them the script. I'm right now just trying to get a massive translation quality right now that works and then will try optimization.
