### ISSUE TITLE
Final Step After Successfull Compile & How to Keep up to date with current FFmpeg release on Win7

### ISSUE THREAD

**Issue by theGuruWithin** [jb-alvarado/media-autobuild_suite#999]
jb, 

Thank you for creating  media-autobuild_suite. 

 I believe I have successfully compiled binaries using your great script using Win7 .... (i decided to compile so i could use better AAC encoder of libfdk_aac but also added so much more available in using your script).  

Since this is the first time I have ever compiled anything... I apologize for my lack of knowledge, but I really need help on the final steps to using the new compiled version instead of the Win64bit versions from  ffmpeg.zeranoe.com.  

Currently when I use the pre-compiled versions from zeranoe.com I just unzip and move the bin folder, doc folder and presets folder to C:\Program Files (open)\ffmpeg\ and add the following to my path.
C:\Program Files (open)\ffmpeg\bin

please note: I keep all opensource and portable source folders in the folder i created C:\Program Files (open)\

So after looking at the local64 folder I just compiled I am confused and not sure with the many more folders and binaries created by compilation which ones to copy into bin folder for ffmpeg or how to organize install and what path to create... to set up newly compiled version properly and usable in my computer's entire path.

Sorry for being such a newbie but really could use your help for this final step....

Also is there an easy way once I have my compiled version installed properly to easily update to current stable release without the hours to compile again from scratch?  Is there a command line for update or script to just update using compiled versions configuration without other changes?

Please help me properly understand how to maintain into the future with keeping all up to date....

in Gratitude,
theGuruWithin

**Comment by wiiaboo** [comment]
If you don't want to waste time compiling, ask zeranoe to make you personal compilations.
Otherwise, learn how to compile manually and then you'd just need incremental compilations most of the time. I am not at all available to hand-hold you through this.

**Comment by 1480c1** [comment]
If you know how to add stuff to your eviroment variables( search it up online as it's helpful to know what they are) you can add the bin-video and bin-audio to your env:Path and that should work for you. IDK about moving the ffmpeg exec to a different folder as the script is designed to look at those folders and rebuild them there. You could try to do a system link from ffmpeg exec and Sox to your program files (open)

**Comment by 1480c1** [comment]
For the updating part, there isn't an easy way to just update ffmpeg with fdk as it's going to be non free, meaning you can't just download it. So you would have to do got pull and rerun the script in the same place. That way it should only update and compile the new stuff instead of compiling everything.

**Comment by theGuruWithin** [comment]
Thank you for the help... where is the best way to learn more so I understand better...

**Comment by 1480c1** [comment]
https://docs.alfresco.com/4.2/tasks/fot-addpath.html For path
https://www.google.co.jp/amp/s/www.howtogeek.com/howto/16226/complete-guide-to-symbolic-links-symlinks-on-windows-or-linux/amp/ For system links
And if you did git clone to get the suite, open CMD or git and do git pull in the folder. IDK about if you downloaded the zip( should be the same, on my phone atm do I can't check). Just run the batch script again after pulling.

**Comment by 1480c1** [comment]
If you want to know more about environment variables and env:Path, just search environment variables or environment variables path on Google and look for either Wikipedia or stack overflow as they usually give a good overview.

**Comment by theGuruWithin** [comment]
Awesome!  

at the very end of the script it says after script is done and isn't running, to drag and drop update_suite.sh on mintty shortcut.  

I was wondering what does this update....

BTW the compiling worked perfectly... I added almost everything in the script and followed the script recommendations for most things that are old or out of date.  That is probably why it took a few hours.  I am running on HP820z with 2 intel xeon CPU ES-2690 v2 @ 3.00GHz processors that run 40 cores... I used 20 as the script suggested....

Sorry for still knowing sooo little, but i work on knowing more everyday.... One day I hope to be able to contribute back to the Open Source world...

As a practical practice how often do you suggest updating or compiling to stay pretty much up to date?

in Gratitude,
tgw

**Comment by 1480c1** [comment]
Not going to lie, I have not used the update script, mainly because when I do update, I just clone the repository to another folder and run the build the so that I can use ffmpeg etc without a worry and then rename the folder back to the same as the first one and rerun the bat file so that everything will be set properly without re editing the path. I just copy the build\media-autobuild_suite.ini so that way I generally don't have to answer the questions again. 

In your case, I would recommend to use around ~30 cores instead of 20 as long as you aren't activity using your computer during the build time as the half cores part is mainly for those who have <8 cores, although it's still not recommended to Use as many cores/threads as you have for building as it will lag your computer to the point that you probably can't watch YouTube. To change this, just edit build/media-autobuild_suite.ini and look for cores=20 and change it to whatever you want and just re run the batch file when you want to update and recompile. It should be slightly faster than before I think.

I personally update when either  wiiaboo adds a commit, ffmpeg throws an error, or after around 2~3 weeks.

I should probably check how to actually use the update script.

**Comment by 1480c1** [comment]
One thing I would first recommend to learn is how to do git clone and git pull on this repository, it's easier for my to run two commands instead of downloading the zip and unzipping everytime there's a update.

**Comment by 1480c1** [comment]
Next thing, I would recommend you to update to at least windows 8 or 10 because Microsoft will stop supporting 7 soon, although there probably will be security updates.

**Comment by theGuruWithin** [comment]
Thank you again for all this great information and for taking the time to educate me....

Happy Holidays good health to you and yours in the coming year.....

TGW

**Comment by 1480c1** [comment]
You too

**Comment by theGuruWithin** [comment]
BTW Update seems to work by running drag and drop update_suite.sh on mintty shortcut!
